# -*- coding: utf-8 -*-
"""SCSSproject_organized.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pPy9e96XDXVGKSJf6PytL7_-m5SAs-u7

# SCSS Project — Zero-Shot and Few-Shot Generalization for Image Editing

1. sample FFHQ images,
2. manually label glasses/facial-hair attributes,
3. build a balanced Phase 1 set,
4. test four prompt strategies,
5. annotate failure modes,
6. select the strongest prompt from Phase 1,
7. compare naive vs. best prompt on a larger clean-image set (CLIP scoring + human pairwise annotation) before LoRA,
8. isolate the remaining facial-hair failures and fine-tune a LoRA adapter on a small set of hand-picked successful edits,
9. grid-search LoRA hyperparameters and pick the best checkpoint by identity-preservation scoring,
10. prototype structure-preserving latent injection as an alternative fix, tuning it via a pilot grid search,
11. compare original vs. best-prompt vs. LoRA vs. latent injection to evaluate final failure-recovery quality.

## 0. Install and imports
"""

#!pip install -q diffusers transformers accelerate safetensors torch torchvision pillow pandas tqdm scipy statsmodels

import os
import json
import random
import shutil
from pathlib import Path

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
from tqdm.auto import tqdm
from scipy.stats import friedmanchisquare, wilcoxon, binomtest
from statsmodels.stats.multitest import multipletests

from diffusers import StableDiffusionInstructPix2PixPipeline, EulerAncestralDiscreteScheduler
from transformers import CLIPProcessor, CLIPModel
import os, random, shutil
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from PIL import Image
import matplotlib.pyplot as plt

from diffusers import StableDiffusionInstructPix2PixPipeline, DDPMScheduler
from diffusers.optimization import get_scheduler
from peft import LoraConfig, get_peft_model
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from transformers import CLIPTextModel, CLIPTokenizer
from accelerate import Accelerator
from tqdm.auto import tqdm

from google.colab import drive
drive.mount('/content/drive')

"""## 1. Configuration

`PHASE2_N_CLEAN_IMAGES` controls how many clean images are used for the two-prompt comparison. Larger values shrink the confidence interval roughly proportional to `1 / sqrt(n)`.

"""

PROJECT_DIR = Path("/content/drive/MyDrive/adobe_phase1_failure_analysis")

RAW_DIR = PROJECT_DIR / "raw_ffhq"
SAMPLE_DIR = PROJECT_DIR / "sample_200_for_labeling"
BALANCED_DIR = PROJECT_DIR / "balanced_ffhq_60"
METADATA_DIR = PROJECT_DIR / "metadata"

CONTACT_DIR = METADATA_DIR / "contact_sheets"
PHASE1_OUTPUT_DIR = PROJECT_DIR / "phase1_outputs"

PHASE2_DIR = PROJECT_DIR / "phase2_naive_vs_best_expanded"
PHASE2_INPUT_DIR = PROJECT_DIR / "phase2_clean_inputs_expanded"
PHASE2_OUTPUT_DIR = PHASE2_DIR / "outputs"

for d in [
    PROJECT_DIR, RAW_DIR, SAMPLE_DIR, BALANCED_DIR, METADATA_DIR,
    CONTACT_DIR, PHASE1_OUTPUT_DIR, PHASE2_DIR, PHASE2_INPUT_DIR, PHASE2_OUTPUT_DIR
]:
    d.mkdir(parents=True, exist_ok=True)

SEED = 42
IMAGE_SIZE = 512

N_LABELING_SAMPLE = 200
TARGET_TOTAL_PHASE1 = 60
N_PER_GROUP_PHASE1 = TARGET_TOTAL_PHASE1 // 4

PHASE2_N_CLEAN_IMAGES = 100

MODEL_ID = "timbrooks/instruct-pix2pix"
CLIP_ID = "openai/clip-vit-base-patch32"

NUM_INFERENCE_STEPS = 50
IMAGE_GUIDANCE_SCALE = 1.5
GUIDANCE_SCALE = 7.5

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

random.seed(SEED)
np.random.seed(SEED)

print("Using device:", device)
print("Project:", PROJECT_DIR)

"""## 2. Download FFHQ dataset

Run this only when the dataset is not already available in `/content/ffhq_dataset`.

"""

# Download and unzip
# !kaggle datasets download -d greatgamedota/ffhq-face-data-set -p /content
# !unzip -q /content/ffhq-face-data-set.zip -d /content/ffhq_dataset

SOURCE_DIR = Path("/content/ffhq_dataset")

all_images = []
for ext in ["*.png", "*.jpg", "*.jpeg"]:
    all_images.extend(SOURCE_DIR.rglob(ext))

all_images = sorted(all_images)

print("Total images found:", len(all_images))
print(all_images[:5])

"""## 3. Create 200-image empirical labeling sample

Manually label a random sample for glasses, facial hair, usability, and notes.

"""

sampled_200 = random.sample(all_images, min(N_LABELING_SAMPLE, len(all_images)))

for f in SAMPLE_DIR.glob("*"):
    if f.is_file():
        f.unlink()

records = []

for i, img_path in enumerate(sampled_200):
    new_name = f"ffhq_sample_{i:04d}{img_path.suffix.lower()}"
    target_path = SAMPLE_DIR / new_name
    shutil.copy2(img_path, target_path)

    records.append({
        "sample_id": f"ffhq_sample_{i:04d}",
        "filename": new_name,
        "image_path": str(target_path),
        "original_path": str(img_path),
    })

df_sample = pd.DataFrame(records)
sample_csv = METADATA_DIR / "sample_200_unlabeled.csv"
df_sample.to_csv(sample_csv, index=False)

print("Saved:", sample_csv)
df_sample.head()

def create_contact_sheet(df, start_idx, end_idx, cols=5, thumb_size=160):
    subset = df.iloc[start_idx:end_idx]
    rows = int(np.ceil(len(subset) / cols))

    fig, axes = plt.subplots(rows, cols, figsize=(cols * 3, rows * 3))
    axes = np.array(axes).reshape(-1)

    for ax, (_, row) in zip(axes, subset.iterrows()):
        img = Image.open(row["image_path"]).convert("RGB")
        img.thumbnail((thumb_size, thumb_size))
        ax.imshow(img)
        ax.set_title(row["sample_id"], fontsize=9)
        ax.axis("off")

    for ax in axes[len(subset):]:
        ax.axis("off")

    plt.tight_layout()
    out_path = CONTACT_DIR / f"contact_{start_idx:03d}_{end_idx-1:03d}.png"
    plt.savefig(out_path, dpi=150)
    plt.show()
    return out_path

for start in range(0, len(df_sample), 25):
    end = min(start + 25, len(df_sample))
    path = create_contact_sheet(df_sample, start, end)
    print("Saved:", path)

df_labels = df_sample.copy()

df_labels["has_glasses"] = ""
df_labels["has_facial_hair"] = ""
df_labels["usable"] = 1
df_labels["notes"] = ""

label_csv = METADATA_DIR / "sample_200_labels_TO_FILL.csv"
df_labels.to_csv(label_csv, index=False)

print("Fill manually:", label_csv)
df_labels.head()

"""## 4. Build balanced Phase 1 set

Labeling samples as having glasses/beard/none and usable/not usable

"""

FILLED_LABEL_CSV = "/content/drive/MyDrive/adobe_phase1_failure_analysis/metadata/sample_200_labels_FILLED.csv"

df = pd.read_csv(FILLED_LABEL_CSV)

for col in ["has_glasses", "has_facial_hair", "usable"]:
    df[col] = df[col].astype(int)

df_usable = df[df["usable"] == 1].copy()

conditions = {
    "no_glasses_no_beard": (df_usable["has_glasses"] == 0) & (df_usable["has_facial_hair"] == 0),
    "glasses_no_beard": (df_usable["has_glasses"] == 1) & (df_usable["has_facial_hair"] == 0),
    "no_glasses_beard": (df_usable["has_glasses"] == 0) & (df_usable["has_facial_hair"] == 1),
    "glasses_beard": (df_usable["has_glasses"] == 1) & (df_usable["has_facial_hair"] == 1),
}

groups = {name: df_usable[condition].copy() for name, condition in conditions.items()}

for name, group_df in groups.items():
    print(name, len(group_df))

balanced_parts = []

for group_name, group_df in groups.items():
    available = len(group_df)
    if available < N_PER_GROUP_PHASE1:
        print(f"Warning: {group_name} only has {available} images, requested {N_PER_GROUP_PHASE1}")

    n = min(N_PER_GROUP_PHASE1, available)
    sampled_group = group_df.sample(n=n, random_state=SEED).copy()
    sampled_group["group"] = group_name
    balanced_parts.append(sampled_group)

df_balanced = pd.concat(balanced_parts).reset_index(drop=True)

for f in BALANCED_DIR.glob("*"):
    if f.is_file():
        f.unlink()

final_records = []

for _, row in df_balanced.iterrows():
    src = Path(row["image_path"])
    new_name = f"{row['group']}_{row['sample_id']}{src.suffix.lower()}"
    dst = BALANCED_DIR / new_name
    shutil.copy2(src, dst)

    record = row.to_dict()
    record["balanced_image_path"] = str(dst)
    record["balanced_filename"] = new_name
    final_records.append(record)

df_final = pd.DataFrame(final_records)
balanced_csv = METADATA_DIR / "balanced_ffhq_metadata.csv"
df_final.to_csv(balanced_csv, index=False)

print("Saved:", balanced_csv)
print("Balanced size:", len(df_final))
df_final["group"].value_counts()

"""## 5. Phase 1: Four-prompt empirical study

Generates all four prompt types on the balanced set.

"""

PROMPT_SETS = {
    "glasses": {
        "naive": "Add glasses.",
        "region_descriptive": "Add black glasses on the person's eyes.",
        "identity_anchored": "Keep the same face and identity, only add black glasses.",
        "negative_constraint": (
            "Add black glasses without changing the person's face, hair, "
            "expression, skin tone, clothing, or background."
        ),
    },
    "facial_hair": {
        "naive": "Add a beard.",
        "region_descriptive": "Add a short beard around the chin and jaw.",
        "identity_anchored": "Keep the same face and identity, only add short facial hair.",
        "negative_constraint": (
            "Add a short beard without changing the person's age, face shape, "
            "hair, expressi on, skin tone, clothing, or background."
        ),
    },
}

def get_image_paths(input_dir):
    valid_exts = {".jpg", ".jpeg", ".png", ".webp"}
    return sorted([p for p in input_dir.iterdir() if p.suffix.lower() in valid_exts])

def load_image(path, size=IMAGE_SIZE):
    image = Image.open(path).convert("RGB")
    return image.resize((size, size))

def load_pix2pix_pipeline():
    pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
        MODEL_ID,
        torch_dtype=dtype,

        safety_checker=None,
    )
    pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)
    pipe = pipe.to(device)
    if device == "cuda":
        pipe.enable_attention_slicing()
    return pipe

pipe = load_pix2pix_pipeline()
print("Model loaded.")

image_paths = get_image_paths(BALANCED_DIR)
print("Phase 1 curated images:", len(image_paths))

records = []

for image_path in tqdm(image_paths, desc="Phase 1 editing"):
    input_image = load_image(image_path)
    image_id = image_path.stem

    for edit_type, prompts in PROMPT_SETS.items():
        for prompt_type, prompt in prompts.items():
            generator = torch.Generator(device=device).manual_seed(SEED)

            result = pipe(
                prompt=prompt,
                image=input_image,
                num_inference_steps=NUM_INFERENCE_STEPS,
                image_guidance_scale=IMAGE_GUIDANCE_SCALE,
                guidance_scale=GUIDANCE_SCALE,
                generator=generator,
            ).images[0]

            edit_dir = PHASE1_OUTPUT_DIR / edit_type / prompt_type
            edit_dir.mkdir(parents=True, exist_ok=True)

            output_filename = f"{image_id}_{edit_type}_{prompt_type}.png"
            output_path = edit_dir / output_filename
            result.save(output_path)

            records.append({
                "image_id": image_id,
                "input_path": str(image_path),
                "output_path": str(output_path),
                "edit_type": edit_type,
                "prompt_type": prompt_type,
                "prompt": prompt,
                "model": MODEL_ID,
                "seed": SEED,
                "num_inference_steps": NUM_INFERENCE_STEPS,
                "image_guidance_scale": IMAGE_GUIDANCE_SCALE,
                "guidance_scale": GUIDANCE_SCALE,
            })

phase1_metadata_json = METADATA_DIR / "generation_metadata.json"
phase1_metadata_csv = METADATA_DIR / "generation_metadata.csv"

with open(phase1_metadata_json, "w", encoding="utf-8") as f:
    json.dump(records, f, indent=2)

pd.DataFrame(records).to_csv(phase1_metadata_csv, index=False)

print("Saved edited images:", len(records))
print("Saved:", phase1_metadata_json)
print("Saved:", phase1_metadata_csv)

"""## 6. Phase 1 manual failure annotation sheet"""

FAILURE_COLUMNS = [
    "edit_success",
    "under_editing",
    "over_editing",
    "identity_drift",
    "localization_error",
    "attribute_entanglement",
    "background_change",
    "expression_change",
    "artifact_distortion",
    "prompt_ignored",
    "notes",
]

df_phase1 = pd.DataFrame(records)

for col in FAILURE_COLUMNS:
    df_phase1[col] = ""

annotation_path = METADATA_DIR / "failure_annotation_sheet.csv"
df_phase1.to_csv(annotation_path, index=False)

print("Annotation sheet saved to:", annotation_path)
df_phase1.head()

def show_all_edits_for_original(image_id, df):
    rows = df[df["image_id"] == image_id].copy()

    if rows.empty:
        print("No edits found for:", image_id)
        return

    original_path = rows.iloc[0]["input_path"]
    original = Image.open(original_path).convert("RGB")
    rows = rows.sort_values(["edit_type", "prompt_type"])

    images = [original]
    titles = ["Original"]

    for _, row in rows.iterrows():
        images.append(Image.open(row["output_path"]).convert("RGB"))
        titles.append(f"{row['edit_type']}\n{row['prompt_type']}")

    n = len(images)
    plt.figure(figsize=(n * 3, 3))

    for i, (img, title) in enumerate(zip(images, titles), start=1):
        plt.subplot(1, n, i)
        plt.imshow(img)
        plt.title(title, fontsize=8)
        plt.axis("off")

    plt.tight_layout()
    plt.show()

for image_id in df_phase1["image_id"].unique():
    show_all_edits_for_original(image_id, df_phase1)

"""## 7. Phase 1 statistics and prompt selection

This analysis preserves how you selected the best prompt empirically.

"""

PHASE1_FILLED_ANNOTATION_CSV = "/content/failure_annotation_sheet_phase1.csv"

df = pd.read_csv(PHASE1_FILLED_ANNOTATION_CSV)
df["edit_success"] = pd.to_numeric(df["edit_success"], errors="coerce")

summary_phase1 = (
    df.groupby(["edit_type", "prompt_type"])["edit_success"]
    .agg(["count", "mean", "std", "median"])
    .reset_index()
    .sort_values(["edit_type", "mean"], ascending=[True, False])
)

summary_phase1

for edit in ["glasses", "facial_hair"]:
    subset = df[df["edit_type"] == edit]

    means = (
        subset.groupby("prompt_type")["edit_success"]
        .mean()
        .sort_values(ascending=False)
    )

    errors = subset.groupby("prompt_type")["edit_success"].std().reindex(means.index)

    plt.figure(figsize=(7, 5))
    means.plot(kind="bar", yerr=errors, capsize=4)
    plt.title(f"{edit}: Mean manual success score")
    plt.ylabel("Mean success score")
    plt.ylim(0, 5)
    plt.xticks(rotation=35, ha="right")
    plt.grid(axis="y", alpha=0.3)
    plt.tight_layout()
    plt.show()

for edit in ["glasses", "facial_hair"]:
    subset = df[df["edit_type"] == edit]
    pivot = subset.pivot_table(index="image_id", columns="prompt_type", values="edit_success")

    stat, p = friedmanchisquare(
        pivot["naive"],
        pivot["region_descriptive"],
        pivot["identity_anchored"],
        pivot["negative_constraint"]
    )

    n = len(pivot)
    k = pivot.shape[1]
    kendalls_w = stat / (n * (k - 1))

    print("\n", edit.upper())
    print("Friedman p =", p)
    print("Kendall's W =", kendalls_w)

    comparisons = []
    p_values = []

    for a, b in __import__("itertools").combinations(pivot.columns.tolist(), 2):
        stat, p_pair = wilcoxon(pivot[a], pivot[b])
        comparisons.append((a, b))
        p_values.append(p_pair)

    corrected = multipletests(p_values, method="holm")[1]

    for (a, b), p_raw, p_corr in zip(comparisons, p_values, corrected):
        print(f"{a} vs {b}: raw p={p_raw:.4f}, Holm p={p_corr:.4f}")

"""### Selected prompts for Phase 2

"""

PHASE2_PROMPTS = {
    "glasses": {
        "naive": "Add glasses.",
        "best": "Keep the same face and identity, only add black glasses."
    },
    "facial_hair": {
        "naive": "Add a beard.",
        "best": "Add a short beard around the chin and jaw."
    }
}

"""## 8. Phase 2 input set

"""

df_labels_filled = pd.read_csv(FILLED_LABEL_CSV)

for col in ["has_glasses", "has_facial_hair", "usable"]:
    df_labels_filled[col] = df_labels_filled[col].astype(int)

df_clean_pool = df_labels_filled[
    (df_labels_filled["usable"] == 1) &
    (df_labels_filled["has_glasses"] == 0) &
    (df_labels_filled["has_facial_hair"] == 0)
].copy()

n_phase2 = min(PHASE2_N_CLEAN_IMAGES, len(df_clean_pool))

if n_phase2 < PHASE2_N_CLEAN_IMAGES:
    print(f"Warning: requested {PHASE2_N_CLEAN_IMAGES}, but only {n_phase2} clean labeled images are available.")

df_phase2_inputs = df_clean_pool.sample(n=n_phase2, random_state=SEED).copy()

for f in PHASE2_INPUT_DIR.glob("*"):
    if f.is_file():
        f.unlink()

input_records = []

for _, row in df_phase2_inputs.iterrows():
    src = Path(row["image_path"])
    dst = PHASE2_INPUT_DIR / f"{row['sample_id']}{src.suffix.lower()}"
    shutil.copy2(src, dst)

    rec = row.to_dict()
    rec["phase2_input_path"] = str(dst)
    input_records.append(rec)

df_phase2_inputs = pd.DataFrame(input_records)
phase2_inputs_csv = PHASE2_DIR / "phase2_clean_inputs_metadata.csv"
df_phase2_inputs.to_csv(phase2_inputs_csv, index=False)

print("Phase 2 clean images:", len(df_phase2_inputs))
print("Saved:", phase2_inputs_csv)
df_phase2_inputs.head()

"""## 9. Expanded Phase 2 generation: naive vs best"""

from diffusers import (
    StableDiffusionInstructPix2PixPipeline,
    EulerAncestralDiscreteScheduler
)

MODEL_ID = "timbrooks/instruct-pix2pix"

IMAGE_SIZE = 512
SEED = 42

NUM_INFERENCE_STEPS = 50
IMAGE_GUIDANCE_SCALE = 1.5
GUIDANCE_SCALE = 7.5

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32

print("Using device:", device)

pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
    MODEL_ID,
    torch_dtype=dtype,
    safety_checker=None,
)

pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(
    pipe.scheduler.config
)

pipe = pipe.to(device)

if device == "cuda":
    pipe.enable_attention_slicing()

print("InstructPix2Pix loaded.")

phase2_records = []

for _, row in tqdm(df_phase2_inputs.iterrows(), total=len(df_phase2_inputs), desc="Phase 2 expanded generation"):
    input_path = Path(row["phase2_input_path"])
    input_image = load_image(input_path, IMAGE_SIZE)
    image_id = row["sample_id"]

    for edit_type, prompt_dict in PHASE2_PROMPTS.items():
        for prompt_type, prompt in prompt_dict.items():
            generator = torch.Generator(device=device).manual_seed(SEED)

            result = pipe(
                prompt=prompt,
                image=input_image,
                num_inference_steps=NUM_INFERENCE_STEPS,
                image_guidance_scale=IMAGE_GUIDANCE_SCALE,
                guidance_scale=GUIDANCE_SCALE,
                generator=generator,
            ).images[0]

            out_dir = PHASE2_OUTPUT_DIR / edit_type / prompt_type
            out_dir.mkdir(parents=True, exist_ok=True)

            output_filename = f"{image_id}_{edit_type}_{prompt_type}.png"
            output_path = out_dir / output_filename
            result.save(output_path)

            phase2_records.append({
                "image_id": image_id,
                "input_path": str(input_path),
                "output_path": str(output_path),
                "edit_type": edit_type,
                "prompt_type": prompt_type,
                "prompt": prompt,
                "model": MODEL_ID,
                "seed": SEED,
                "num_inference_steps": NUM_INFERENCE_STEPS,
                "image_guidance_scale": IMAGE_GUIDANCE_SCALE,
                "guidance_scale": GUIDANCE_SCALE,
            })

df_phase2 = pd.DataFrame(phase2_records)
phase2_generation_csv = PHASE2_DIR / "phase2_generation_metadata.csv"
df_phase2.to_csv(phase2_generation_csv, index=False)

print("Saved:", phase2_generation_csv)
print(df_phase2.shape)
df_phase2.head()

"""## 10. CLIP scoring for Phase 2"""

clip_model = CLIPModel.from_pretrained(CLIP_ID).to(device)
clip_processor = CLIPProcessor.from_pretrained(CLIP_ID)
clip_model.eval()

def clip_text_probs(image_path, labels):
    image = Image.open(image_path).convert("RGB")

    inputs = clip_processor(
        text=labels,
        images=image,
        return_tensors="pt",
        padding=True
    ).to(device)

    with torch.no_grad():
        outputs = clip_model(**inputs)
        probs = outputs.logits_per_image.softmax(dim=1)[0].detach().cpu().numpy()

    return dict(zip(labels, probs))

def clip_image_similarity(path_a, path_b):
    image_a = Image.open(path_a).convert("RGB")
    image_b = Image.open(path_b).convert("RGB")

    inputs_a = clip_processor(images=image_a, return_tensors="pt").to(device)
    inputs_b = clip_processor(images=image_b, return_tensors="pt").to(device)

    with torch.no_grad():
        out_a = clip_model.get_image_features(**inputs_a)
        out_b = clip_model.get_image_features(**inputs_b)

        if hasattr(out_a, "image_embeds"):
            emb_a = out_a.image_embeds
            emb_b = out_b.image_embeds
        elif hasattr(out_a, "pooler_output"):
            emb_a = out_a.pooler_output
            emb_b = out_b.pooler_output
        else:
            emb_a = out_a
            emb_b = out_b

        emb_a = emb_a / emb_a.norm(dim=-1, keepdim=True)
        emb_b = emb_b / emb_b.norm(dim=-1, keepdim=True)

        sim = (emb_a @ emb_b.T).item()

    return sim

clip_records = []

for _, row in tqdm(df_phase2.iterrows(), total=len(df_phase2), desc="CLIP scoring"):
    if row["edit_type"] == "glasses":
        labels = ["a person wearing glasses", "a person without glasses"]
        positive_label = "a person wearing glasses"
        negative_label = "a person without glasses"
    else:
        labels = ["a person with facial hair", "a person without facial hair"]
        positive_label = "a person with facial hair"
        negative_label = "a person without facial hair"

    probs = clip_text_probs(row["output_path"], labels)

    target_score = probs[positive_label]
    contrast_score = probs[positive_label] - probs[negative_label]
    preservation_score = clip_image_similarity(row["input_path"], row["output_path"])

    clip_records.append({
        **row.to_dict(),
        "clip_target_score": target_score,
        "clip_negative_score": probs[negative_label],
        "clip_contrast_score": contrast_score,
        "clip_preservation_score": preservation_score,
    })

df_clip = pd.DataFrame(clip_records)
phase2_clip_csv = PHASE2_DIR / "phase2_clip_results.csv"
df_clip.to_csv(phase2_clip_csv, index=False)

print("Saved:", phase2_clip_csv)
df_clip.head()

"""## 11. Confidence intervals and paired tests

This section reports mean differences between best and naive prompts with bootstrap 95% confidence intervals.

Positive difference means the **best** prompt is better than the naive prompt.

"""

def paired_metric_table(df_clip, metric, n_boot=5000, seed=SEED):
    rng = np.random.default_rng(seed)
    rows = []

    for edit_type in ["glasses", "facial_hair"]:
        subset = df_clip[df_clip["edit_type"] == edit_type]
        pivot = subset.pivot_table(index="image_id", columns="prompt_type", values=metric).dropna()

        diff = pivot["best"] - pivot["naive"]
        n = len(diff)

        boot_means = []
        values = diff.to_numpy()

        for _ in range(n_boot):
            sample = rng.choice(values, size=n, replace=True)
            boot_means.append(sample.mean())

        ci_low, ci_high = np.percentile(boot_means, [2.5, 97.5])

        stat, p_two_sided = wilcoxon(pivot["best"], pivot["naive"], alternative="two-sided")
        stat, p_greater = wilcoxon(pivot["best"], pivot["naive"], alternative="greater")

        rows.append({
            "edit_type": edit_type,
            "metric": metric,
            "n_pairs": n,
            "mean_best": pivot["best"].mean(),
            "mean_naive": pivot["naive"].mean(),
            "mean_diff_best_minus_naive": diff.mean(),
            "ci95_low": ci_low,
            "ci95_high": ci_high,
            "wilcoxon_p_two_sided": p_two_sided,
            "wilcoxon_p_best_greater": p_greater,
        })

    return pd.DataFrame(rows)

tables = []

for metric in ["clip_target_score", "clip_contrast_score", "clip_preservation_score"]:
    tables.append(paired_metric_table(df_clip, metric))

phase2_stats = pd.concat(tables, ignore_index=True)
phase2_stats_csv = PHASE2_DIR / "phase2_paired_stats_with_bootstrap_ci.csv"
phase2_stats.to_csv(phase2_stats_csv, index=False)

print("Saved:", phase2_stats_csv)
phase2_stats

def plot_paired_differences_with_ci(stats_df, metric):
    sub = stats_df[stats_df["metric"] == metric].copy()

    x = np.arange(len(sub))
    means = sub["mean_diff_best_minus_naive"].to_numpy()
    lower = means - sub["ci95_low"].to_numpy()
    upper = sub["ci95_high"].to_numpy() - means

    plt.figure(figsize=(7, 5))
    plt.bar(x, means, yerr=[lower, upper], capsize=5)
    plt.axhline(0, linestyle="--", linewidth=1)
    plt.xticks(x, sub["edit_type"].str.replace("_", " ").str.title())
    plt.ylabel("Best - Naive")
    plt.title(f"Paired Difference with 95% Bootstrap CI\n{metric}")
    plt.grid(axis="y", alpha=0.3)
    plt.tight_layout()
    plt.show()

for metric in ["clip_target_score", "clip_contrast_score", "clip_preservation_score"]:
    plot_paired_differences_with_ci(phase2_stats, metric)

"""## 12. Manual pairwise annotation sheet for expanded Phase 2

This keeps your manual qualitative comparison format but applies it to the larger Phase 2 sample.

"""

phase2_manual = []

for image_id in sorted(df_clip["image_id"].unique()):
    for edit_type in ["glasses", "facial_hair"]:
        phase2_manual.append({
            "image_id": image_id,
            "edit_type": edit_type,
            "overall_better": "",
            "identity_preservation": "",
            "edit_strength": "",
            "realism": "",
            "notes": ""
        })

df_phase2_manual = pd.DataFrame(phase2_manual)
phase2_manual_csv = PHASE2_DIR / "phase2_pairwise_annotation_TO_FILL.csv"
df_phase2_manual.to_csv(phase2_manual_csv, index=False)

print("Saved:", phase2_manual_csv)
df_phase2_manual.head()

def show_pair_for_annotation(image_id, edit_type, df_clip):
    rows = df_clip[
        (df_clip["image_id"] == image_id) &
        (df_clip["edit_type"] == edit_type)
    ]

    if rows.empty:
        print("No rows found:", image_id, edit_type)
        return

    original_path = rows.iloc[0]["input_path"]

    naive_row = rows[rows["prompt_type"] == "naive"].iloc[0]
    best_row = rows[rows["prompt_type"] == "best"].iloc[0]

    images = [
        Image.open(original_path).convert("RGB"),
        Image.open(naive_row["output_path"]).convert("RGB"),
        Image.open(best_row["output_path"]).convert("RGB"),
    ]

    titles = [
        "Original",
        f"Naive\nTarget={naive_row['clip_target_score']:.2f}\nPres={naive_row['clip_preservation_score']:.2f}",
        f"Best\nTarget={best_row['clip_target_score']:.2f}\nPres={best_row['clip_preservation_score']:.2f}",
    ]

    plt.figure(figsize=(12, 4))

    for i, (img, title) in enumerate(zip(images, titles), start=1):
        plt.subplot(1, 3, i)
        plt.imshow(img)
        plt.title(title, fontsize=11)
        plt.axis("off")

    plt.suptitle(f"{image_id} — {edit_type}", fontsize=14, fontweight="bold")
    plt.tight_layout()
    plt.show()

for image_id in sorted(df_clip["image_id"].unique()):
    for edit_type in ["glasses", "facial_hair"]:
        show_pair_for_annotation(image_id, edit_type, df_clip)
        print("Annotate this row:")
        print(f"image_id = {image_id}, edit_type = {edit_type}")
        print("overall_better: naive / best / tie")
        print("identity_preservation: naive / best / tie")
        print("edit_strength: naive / best / tie")
        print("realism: naive / best / tie")
        print("-" * 80)

"""## 13. Manual pairwise annotation analysis with confidence intervals"""

PHASE2_MANUAL_FILLED_CSV = "/content/phase2_pairwise_annotation_FILLED.csv"

df_pair = pd.read_csv(PHASE2_MANUAL_FILLED_CSV)

DIMS = ["overall_better", "identity_preservation", "edit_strength", "realism"]
EDIT_TYPES = ["glasses", "facial_hair"]

def count_preferences(df, edit_type):
    sub = df[df["edit_type"] == edit_type]
    results = {}

    for dim in DIMS:
        vc = sub[dim].value_counts()
        results[dim] = {
            "naive": vc.get("naive", 0),
            "best": vc.get("best", 0),
            "tie": vc.get("tie", 0),
        }

    return results, len(sub)

manual_rows = []

for edit_type in EDIT_TYPES:
    prefs, n_total = count_preferences(df_pair, edit_type)

    for dim in DIMS:
        n_best = prefs[dim]["best"]
        n_naive = prefs[dim]["naive"]
        n_tie = prefs[dim]["tie"]
        n_no_tie = n_best + n_naive

        if n_no_tie > 0:
            result = binomtest(n_best, n_no_tie, p=0.5, alternative="greater")
            ci = result.proportion_ci(confidence_level=0.95, method="wilson")
            best_win_rate = n_best / n_no_tie
            p_value = result.pvalue
            ci_low = ci.low
            ci_high = ci.high
        else:
            best_win_rate = np.nan
            p_value = np.nan
            ci_low = np.nan
            ci_high = np.nan

        manual_rows.append({
            "edit_type": edit_type,
            "dimension": dim,
            "n_total": n_total,
            "n_best": n_best,
            "n_naive": n_naive,
            "n_tie": n_tie,
            "n_excluding_ties": n_no_tie,
            "best_win_rate_excluding_ties": best_win_rate,
            "ci95_low": ci_low,
            "ci95_high": ci_high,
            "binomial_p_best_greater": p_value,
        })

manual_stats = pd.DataFrame(manual_rows)
manual_stats_csv = PHASE2_DIR / "phase2_manual_pairwise_stats_with_ci.csv"
manual_stats.to_csv(manual_stats_csv, index=False)

print("Saved:", manual_stats_csv)
manual_stats

for edit_type in EDIT_TYPES:
    prefs, n = count_preferences(df_pair, edit_type)

    x = np.arange(len(DIMS))
    naive_vals = [prefs[d]["naive"] for d in DIMS]
    tie_vals = [prefs[d]["tie"] for d in DIMS]
    best_vals = [prefs[d]["best"] for d in DIMS]

    plt.figure(figsize=(9, 5))
    plt.bar(x, naive_vals, label="Naive")
    plt.bar(x, tie_vals, bottom=naive_vals, label="Tie")
    plt.bar(x, best_vals, bottom=np.array(naive_vals) + np.array(tie_vals), label="Best")

    plt.xticks(x, [d.replace("_", "\n") for d in DIMS])
    plt.ylabel("Number of annotations")
    plt.title(f"Pairwise preference: {edit_type}")
    plt.legend()
    plt.tight_layout()
    plt.show()

def make_merged(edit_type):
    naive = df_clip[(df_clip.edit_type == edit_type) & (df_clip.prompt_type == "naive")].set_index("image_id")
    best  = df_clip[(df_clip.edit_type == edit_type) & (df_clip.prompt_type == "best")].set_index("image_id")
    diff  = pd.DataFrame({
        "clip_contrast_diff":     best["clip_contrast_score"]     - naive["clip_contrast_score"],
        "clip_preservation_diff": best["clip_preservation_score"] - naive["clip_preservation_score"],
    }).reset_index()
    human = df_pair[df_pair.edit_type == edit_type][["image_id"] + DIMS]
    return human.merge(diff, on="image_id")

import pandas as pd
import numpy as np

clip = pd.read_csv("phase2_clip_results.csv")
ann = pd.read_csv("phase2_pairwise_annotation_FILLED.csv")

pivot = clip.pivot_table(
    index=["image_id", "edit_type"],
    columns="prompt_type",
    values=["clip_target_score", "clip_preservation_score"]
)

pivot.columns = ["_".join(c) for c in pivot.columns]
pivot = pivot.reset_index()

pivot["clip_edit_winner"] = np.where(
    pivot["clip_target_score_best"] >
    pivot["clip_target_score_naive"],
    "best",
    "naive"
)

merged = ann.merge(
    pivot,
    on=["image_id", "edit_type"]
)

agreement = (
    merged["edit_strength"] ==
    merged["clip_edit_winner"]
).mean()

print("Agreement:", agreement)

import matplotlib.patches as mpatches
from scipy import stats

df_clip = pd.read_csv("/content/phase2_clip_results.csv")

EDIT_TYPES = ["glasses", "facial_hair"]
DIMS       = ["overall_better", "identity_preservation", "edit_strength", "realism"]
DIM_LABELS = ["Overall\nbetter", "Identity\npreservation", "Edit\nstrength", "Realism"]

PREF_COLORS = {"best": "#378ADD", "naive": "#E24B4A", "tie": "#AAAAAA"}
PREF_ORDER  = ["best", "tie", "naive"]

EDIT_LABELS = {"glasses": "Glasses", "facial_hair": "Facial hair"}


# ══════════════════════════════════════════════════════════════════════════════
# PLOT 1 — Scatter: Δ CLIP contrast vs human overall_better, per edit type
# ══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(12, 5), sharey=False)
fig.suptitle(
    "Plot 1 — Δ CLIP contrast (best − naive) per image vs human overall preference",
    fontsize=13, fontweight="bold", y=1.01,
)

JITTER_Y = {"best": 1, "tie": 0, "naive": -1}
JITTER_AMT = 0.18

for ax, edit in zip(axes, EDIT_TYPES):
    df = make_merged(edit)

    # Spearman r for annotation
    num_map = {"best": 1, "tie": 0, "naive": -1}
    y_num   = df["overall_better"].map(num_map)
    r, p    = stats.spearmanr(df["clip_contrast_diff"], y_num)

    rng = np.random.default_rng(42)
    for pref in PREF_ORDER:
        sub = df[df["overall_better"] == pref]
        y_jit = JITTER_Y[pref] + rng.uniform(-JITTER_AMT, JITTER_AMT, len(sub))
        ax.scatter(
            sub["clip_contrast_diff"], y_jit,
            color=PREF_COLORS[pref], alpha=0.55, s=28, linewidths=0,
            label=f"{pref.capitalize()} (n={len(sub)})",
            zorder=3,
        )

    # trend line
    x_all = df["clip_contrast_diff"].values
    slope, intercept, *_ = stats.linregress(x_all, y_num)
    x_line = np.linspace(x_all.min(), x_all.max(), 100)
    ax.plot(x_line, slope * x_line + intercept,
            color="#333333", lw=1.4, ls="--", zorder=4, label=f"Trend (r={r:.2f}, p={p:.3f})")

    ax.axvline(0, color="#CCCCCC", lw=1, zorder=1)
    ax.set_yticks([-1, 0, 1])
    ax.set_yticklabels(["naive preferred", "tie", "best preferred"], fontsize=10)
    ax.set_xlabel("Δ CLIP contrast score  (best − naive)", fontsize=10)
    ax.set_title(EDIT_LABELS[edit], fontsize=11, fontweight="bold")
    ax.legend(fontsize=8, loc="upper left")
    ax.grid(axis="x", alpha=0.3)
    ax.set_facecolor("#FAFAFA")

    # annotation box
    ax.text(
        0.97, 0.05,
        f"Spearman r = {r:.2f}\np = {p:.3f}",
        transform=ax.transAxes, fontsize=9,
        ha="right", va="bottom",
        bbox=dict(boxstyle="round,pad=0.3", fc="white", ec="#CCCCCC", alpha=0.8),
    )

plt.tight_layout()
plt.savefig("plot1_scatter_clip_vs_human_overall.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved: plot1_scatter_clip_vs_human_overall.png")


# ══════════════════════════════════════════════════════════════════════════════
# PLOT 2 — Grouped bar: mean Δ CLIP contrast per (dimension × human preference)
# ══════════════════════════════════════════════════════════════════════════════
fig, axes = plt.subplots(1, 2, figsize=(13, 5), sharey=True)
fig.suptitle(
    "Plot 2 — Mean Δ CLIP contrast by human preference dimension\n"
    "(positive = CLIP favours best; negative = CLIP favours naive)",
    fontsize=13, fontweight="bold", y=1.02,
)

BAR_W = 0.22
OFFSETS = {"best": -BAR_W, "tie": 0, "naive": BAR_W}

for ax, edit in zip(axes, EDIT_TYPES):
    df = make_merged(edit)
    x  = np.arange(len(DIMS))

    for pref, offset in OFFSETS.items():
        means, errs = [], []
        for dim in DIMS:
            sub = df[df[dim] == pref]["clip_contrast_diff"]
            means.append(sub.mean() if len(sub) > 0 else 0)
            errs.append(sub.sem()   if len(sub) > 1 else 0)

        ax.bar(
            x + offset, means,
            width=BAR_W, color=PREF_COLORS[pref], alpha=0.85,
            label=f"{pref.capitalize()}",
            yerr=errs, capsize=3, error_kw={"elinewidth": 1, "ecolor": "#555"},
            zorder=3,
        )

    ax.axhline(0, color="#666666", lw=0.8, zorder=2)
    ax.set_xticks(x)
    ax.set_xticklabels(DIM_LABELS, fontsize=10)
    ax.set_ylabel("Mean Δ CLIP contrast (best − naive)", fontsize=10)
    ax.set_title(EDIT_LABELS[edit], fontsize=11, fontweight="bold")
    ax.legend(fontsize=9, title="Human preference", title_fontsize=9)
    ax.grid(axis="y", alpha=0.3)
    ax.set_facecolor("#FAFAFA")

    # annotate the key finding per edit
    if edit == "glasses":
        note = "CLIP only tracks edit strength,\nnot overall quality or realism"
    else:
        note = "CLIP contrast is negative even\nwhere humans prefer 'best'"

    ax.text(
        0.97, 0.97, note,
        transform=ax.transAxes, fontsize=8.5,
        ha="right", va="top",
        bbox=dict(boxstyle="round,pad=0.35", fc="white", ec="#CCCCCC", alpha=0.85),
    )

plt.tight_layout()
plt.savefig("plot2_grouped_bar_clip_by_dimension.png", dpi=150, bbox_inches="tight")
plt.show()
print("Saved: plot2_grouped_bar_clip_by_dimension.png")

"""## Phase 3- LoRA on failed examples

"""

# !pip install -q diffusers transformers accelerate safetensors torch torchvision pillow pandas tqdm scipy statsmodels

import os
import json
import random
import shutil
from pathlib import Path

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
from tqdm.auto import tqdm
from scipy.stats import friedmanchisquare, wilcoxon, binomtest
from statsmodels.stats.multitest import multipletests

from diffusers import StableDiffusionInstructPix2PixPipeline, EulerAncestralDiscreteScheduler
from transformers import CLIPProcessor, CLIPModel
import os, random, shutil
from pathlib import Path

import numpy as np
import pandas as pd
import torch
from PIL import Image
import matplotlib.pyplot as plt

from diffusers import StableDiffusionInstructPix2PixPipeline, DDPMScheduler
from diffusers.optimization import get_scheduler
from peft import LoraConfig, get_peft_model
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from transformers import CLIPTextModel, CLIPTokenizer
from accelerate import Accelerator
from tqdm.auto import tqdm

from google.colab import drive
drive.mount('/content/drive')

# !pip install -q diffusers transformers accelerate peft datasets bitsandbytes

"""
 LoRA fine-tuning of instruct-pix2pix on facial-hair failures

1. Build a small training set from your BEST successful beard edits
   (5-6 examples selected by CLIP preservation + human annotation quality).
2. Fine-tune only the UNet cross-attention layers with LoRA (~3M params).
3. Re-run inference on the flagged fail/semi-fail images with the LoRA adapter.
4. Evaluate with CLIP scores and optionally re-annotate.

"""


PHASE2_DIR       = Path("/content/drive/MyDrive/adobe_phase1_failure_analysis")
INPUTS_DIR       = PHASE2_DIR / "phase2_clean_inputs_expanded"        # 100 original faces
OUTPUTS_DIR      = PHASE2_DIR / "phase2_naive_vs_best_expanded/outputs/facial_hair/best"
ANNOTATION_CSV   = PHASE2_DIR / "phase2_naive_vs_best_expanded/phase2_pairwise_annotation_FILLED.csv"
CLIP_CSV         = PHASE2_DIR / "phase2_naive_vs_best_expanded/phase2_clip_results.csv"
LORA_OUTPUT_DIR  = PHASE2_DIR / "phase3_lora_facial_hair"

LORA_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

EDIT_PROMPT = "Add a short beard around the chin and jaw"
MODEL_ID    = "timbrooks/instruct-pix2pix"
SEED        = 42

df_ann  = pd.read_csv(ANNOTATION_CSV)
df_clip = pd.read_csv(CLIP_CSV)

# Failures to fix
df_fails = df_ann[
    (df_ann.edit_type == "facial_hair") &
    (df_ann.notes.isin(["fail", "semi-fail"]))
].copy()
print(f"Failures to fix: {len(df_fails)}")
print(df_fails[["image_id", "notes", "overall_better", "edit_strength", "realism"]].to_string())

# Clean successes pool (overall best, good identity, good realism, no fail note)
df_success = df_ann[
    (df_ann.edit_type == "facial_hair") &
    (~df_ann.notes.isin(["fail", "semi-fail"])) &
    (df_ann.overall_better == "best") &
    (df_ann.identity_preservation.isin(["best", "tie"])) &
    (df_ann.realism == "best")
].copy()
print(f"\nClean success pool: {len(df_success)}")

MANUAL_PICKS = [
    "ffhq_sample_0055",
    "ffhq_sample_0032",
    "ffhq_sample_0031",
    "ffhq_sample_0158",
    "ffhq_sample_0064",
    "ffhq_sample_0128",
    "ffhq_sample_0173",
    "ffhq_sample_0178",
    "ffhq_sample_0197",
    "ffhq_sample_0154",
]

missing = [p for p in MANUAL_PICKS if p not in df_success["image_id"].values]
assert not missing, f"Not in success pool (check spelling): {missing}"
assert len(MANUAL_PICKS) >= 4, "Pick at least 4."

df_train = df_success[df_success["image_id"].isin(MANUAL_PICKS)].copy()
print(f"Training set: {len(df_train)} examples")
print(df_train[["image_id", "identity_preservation", "realism"]].to_string())

def load_image(path, size=256):
    return Image.open(path).convert("RGB").resize((size, size), Image.LANCZOS)

fig, axes = plt.subplots(len(df_train), 2, figsize=(6, len(df_train) * 3))
for i, (_, row) in enumerate(df_train.iterrows()):
    inp = load_image(INPUTS_DIR / f"{row.image_id}.png")
    out_path = OUTPUTS_DIR / f"{row.image_id}_facial_hair_best.png"
    out = load_image(out_path)
    axes[i, 0].imshow(inp);  axes[i, 0].axis("off")
    axes[i, 1].imshow(out);  axes[i, 1].axis("off")
    if i == 0:
        axes[i, 0].set_title("Input", fontsize=10)
        axes[i, 1].set_title("Target (best edit)", fontsize=10)
    axes[i, 0].set_ylabel(row.image_id, fontsize=8, rotation=0, labelpad=60, va="center")

plt.suptitle("LoRA training pairs", fontsize=12, fontweight="bold")
plt.tight_layout()
plt.show()

from PIL import Image
import cv2
import numpy as np

RESOLUTION = 256

def pil_to_np(img):
    return np.array(img.convert("RGB")).astype(np.float32) / 255.0

def np_to_pil(arr):
    arr = np.clip(arr * 255.0, 0, 255).astype(np.uint8)
    return Image.fromarray(arr)

def normalize_pair(orig_img, edit_img):
    orig_np = pil_to_np(orig_img)
    edit_np = pil_to_np(edit_img)

    # ensure contiguous float32 — OpenCV is strict about this
    orig_np = np.ascontiguousarray(orig_np, dtype=np.float32)
    edit_np = np.ascontiguousarray(edit_np, dtype=np.float32)

    orig_ycc = cv2.cvtColor(orig_np, cv2.COLOR_RGB2YCrCb)
    edit_ycc = cv2.cvtColor(edit_np, cv2.COLOR_RGB2YCrCb)

    y_edit = edit_ycc[:,:,0]
    y_orig = orig_ycc[:,:,0]

    y_edit_norm = (y_edit - y_edit.mean()) / (y_edit.std() + 1e-6)
    y_edit_norm = y_edit_norm * y_orig.std() + y_orig.mean()

    edit_ycc[:,:,0] = np.clip(y_edit_norm, 0, 1)
    edit_normalized = cv2.cvtColor(
        np.ascontiguousarray(edit_ycc, dtype=np.float32),  # contiguous before converting back
        cv2.COLOR_YCrCb2RGB
    )
    return np_to_pil(edit_normalized)

class InstructEditDataset(Dataset):
    def __init__(self, df, inputs_dir, outputs_dir, prompt, resolution=256):
        self.records     = df.reset_index(drop=True)
        self.inputs_dir  = Path(inputs_dir)
        self.outputs_dir = Path(outputs_dir)
        self.prompt      = prompt
        self.to_tensor   = transforms.Compose([
            transforms.Resize(resolution, interpolation=transforms.InterpolationMode.LANCZOS),
            transforms.CenterCrop(resolution),
            transforms.ToTensor(),
            transforms.Normalize([0.5], [0.5]),
        ])

    def __len__(self):
        return len(self.records)

    def __getitem__(self, idx):
        row  = self.records.iloc[idx]
        orig = Image.open(self.inputs_dir / f"{row.image_id}.png").convert("RGB")
        edit = Image.open(self.outputs_dir / f"{row.image_id}_facial_hair_best.png").convert("RGB")

        edit = normalize_pair(orig, edit)  # ← only change from your original

        if torch.rand(1) > 0.5:
            brightness = 0.9 + torch.rand(1).item() * 0.2
            contrast   = 0.9 + torch.rand(1).item() * 0.2
            orig = transforms.functional.adjust_brightness(orig, brightness)
            edit = transforms.functional.adjust_brightness(edit, brightness)  # same value
            orig = transforms.functional.adjust_contrast(orig, contrast)
            edit = transforms.functional.adjust_contrast(edit, contrast)      # same value

        return {
            "original_pixel_values": self.to_tensor(orig),
            "edited_pixel_values":   self.to_tensor(edit),
            "input_ids":             self.prompt,
        }


train_dataset = InstructEditDataset(
    df_train, INPUTS_DIR, OUTPUTS_DIR, EDIT_PROMPT, resolution=RESOLUTION
)
print(f"Dataset size: {len(train_dataset)}")

# !pip install -q torchao==0.16.0

print("Loading model...")
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float32,   # fp32 for fine-tuning stability; switch to fp16 for inference
    safety_checker=None,
)

# Freeze everything except LoRA params
pipe.vae.requires_grad_(False)
pipe.text_encoder.requires_grad_(False)
pipe.unet.requires_grad_(False)

# LoRA config: target cross-attention projections in the UNet
# attn_to_{q,k,v,out} in both self- and cross-attention blocks
lora_config = LoraConfig(
    r=8,            # was 8 — less memorization capacity for small dataset
    lora_alpha=8,   # keep scale = alpha/r = 1.0
    target_modules=["to_q", "to_k", "to_v", "to_out.0"],  # drop to_k and to_out.0
    lora_dropout=0.05,  # was 0.05 — more regularization
    bias="none",
)

pipe.unet = get_peft_model(pipe.unet, lora_config)
pipe.unet.print_trainable_parameters()

tokenizer    = pipe.tokenizer
text_encoder = pipe.text_encoder
vae          = pipe.vae
unet         = pipe.unet
noise_sched  = DDPMScheduler.from_pretrained(MODEL_ID, subfolder="scheduler")

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

def encode_text(prompt):
    tokens = tokenizer(
        prompt,
        padding="max_length",
        max_length=tokenizer.model_max_length,
        truncation=True,
        return_tensors="pt",
    ).input_ids.to(accelerator.device)
    with torch.no_grad():
        return text_encoder(tokens).last_hidden_state

import torch.nn.functional as F

# ── Hyper-parameters ──────────────────────────────────────────────────────────
NUM_EPOCHS        = 120
LR                = 5e-6
BATCH_SIZE        = 1
GRAD_ACCUM_STEPS  = 4
MAX_GRAD_NORM     = 1.0
MIXED_PRECISION   = "no"

accelerator = Accelerator(
    gradient_accumulation_steps=GRAD_ACCUM_STEPS,
    mixed_precision=MIXED_PRECISION,
)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)

optimizer = torch.optim.AdamW(
    filter(lambda p: p.requires_grad, unet.parameters()),
    lr=LR,
    weight_decay=1e-4,
    betas=(0.9, 0.999),
)

lr_scheduler = get_scheduler(
    "constant_with_warmup",
    optimizer=optimizer,
    num_warmup_steps=50,
    num_training_steps=NUM_EPOCHS * len(train_loader),
)

unet, optimizer, train_loader, lr_scheduler = accelerator.prepare(
    unet, optimizer, train_loader, lr_scheduler
)
vae.to(accelerator.device)
text_encoder.to(accelerator.device)

# Training loop
losses      = []
best_loss   = float("inf")

unet.train()

for epoch in tqdm(range(NUM_EPOCHS), desc="Epochs"):
    epoch_loss = 0.0

    for batch in train_loader:
        with accelerator.accumulate(unet):
            orig_px = batch["original_pixel_values"].to(accelerator.device)
            edit_px = batch["edited_pixel_values"].to(accelerator.device)

            orig_latents = vae.encode(orig_px).latent_dist.sample() * vae.config.scaling_factor
            edit_latents = vae.encode(edit_px).latent_dist.sample() * vae.config.scaling_factor

            noise     = torch.randn_like(edit_latents)
            bsz       = edit_latents.shape[0]
            timesteps = torch.randint(
                0, noise_sched.config.num_train_timesteps,
                (bsz,), device=accelerator.device,
            ).long()
            noisy_latents = noise_sched.add_noise(edit_latents, noise, timesteps)

            model_input           = torch.cat([noisy_latents, orig_latents], dim=1)
            encoder_hidden_states = encode_text(EDIT_PROMPT)

            noise_pred = unet(
                model_input,
                timesteps,
                encoder_hidden_states=encoder_hidden_states,
            ).sample

            loss = F.mse_loss(noise_pred, noise)

            accelerator.backward(loss)
            accelerator.clip_grad_norm_(unet.parameters(), MAX_GRAD_NORM)
            optimizer.step()
            lr_scheduler.step()
            optimizer.zero_grad()

            epoch_loss += loss.item()

    avg_loss = epoch_loss / len(train_loader)
    losses.append(avg_loss)

    if avg_loss < best_loss:
        best_loss = avg_loss
        unet.save_pretrained(LORA_OUTPUT_DIR / "unet_lora_best")

    if epoch % 10 == 0:
        print(f"Epoch {epoch:3d} | loss {avg_loss:.4f} | lr {lr_scheduler.get_last_lr()[0]:.2e}")

# Plot
plt.figure(figsize=(8, 3))
plt.plot(losses)
plt.xlabel("Epoch"); plt.ylabel("MSE loss")
plt.title("LoRA fine-tuning loss"); plt.grid(alpha=0.3)
plt.tight_layout(); plt.show()

print(f"Best checkpoint → {LORA_OUTPUT_DIR / 'unet_lora_best'} (loss {best_loss:.4f})")

del pipe
torch.cuda.empty_cache()

print("Building inference pipeline with LoRA adapter...")

pipe_lora = StableDiffusionInstructPix2PixPipeline.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.float16,
    safety_checker=None,
).to(device)

pipe_lora.unet = get_peft_model(pipe_lora.unet, lora_config)
pipe_lora.unet.load_adapter(
    str(LORA_OUTPUT_DIR / "unet_lora_best"),
    adapter_name="default"
)

IMAGE_GUIDANCE_SCALE = 1.7   # higher = stronger identity anchor
GUIDANCE_SCALE       = 7.5   # lowered from 7.5 — less aggressive edit
INFERENCE_STEPS      = 25    # more steps = cleaner texture

LORA_OUTPUTS_DIR = PHASE2_DIR / "phase3_lora_facial_hair" / "outputs"
LORA_OUTPUTS_DIR.mkdir(parents=True, exist_ok=True)

lora_results = []
print(f"Running inference on {len(df_fails)} failures...")


for _, row in tqdm(df_fails.iterrows(), total=len(df_fails)):
    input_img = Image.open(INPUTS_DIR / f"{row.image_id}.png").convert("RGB").resize(
        (RESOLUTION, RESOLUTION), Image.LANCZOS
    )

    best_result = None
    for seed in [42, 123, 777]:
        generator = torch.Generator(device=device).manual_seed(seed)
        with torch.autocast(device):
            result = pipe_lora(
                prompt=EDIT_PROMPT,
                image=input_img,
                num_inference_steps=INFERENCE_STEPS,
                image_guidance_scale=IMAGE_GUIDANCE_SCALE,
                guidance_scale=GUIDANCE_SCALE,
                generator=generator,
            ).images[0]

        out_path = LORA_OUTPUTS_DIR / f"{row.image_id}_facial_hair_lora_seed{seed}.png"
        result.save(out_path)  # raw output — no post-processing

        if seed == 42:
            best_result = result
            best_path = LORA_OUTPUTS_DIR / f"{row.image_id}_facial_hair_lora.png"
            best_result.save(best_path)

    lora_results.append({"image_id": row.image_id, "output_path": str(best_path)})

df_lora_results = pd.DataFrame(lora_results)
df_lora_results.to_csv(LORA_OUTPUT_DIR / "phase3_lora_results.csv", index=False)
print(f"Saved {len(df_lora_results)} outputs (3 seeds each).")

def show_comparison(image_id, df_clip, lora_outputs_dir, inputs_dir, outputs_dir, n=10):
    """Show original / best-prompt output / LoRA output side-by-side."""
    rows = df_clip[
        (df_clip.image_id == image_id) &
        (df_clip.edit_type == "facial_hair")
    ]
    orig_path = rows.iloc[0]["input_path"]
    best_path = rows[rows.prompt_type == "best"].iloc[0]["output_path"]
    lora_path = lora_outputs_dir / f"{image_id}_facial_hair_lora.png"

    images = [
        Image.open(orig_path).convert("RGB"),
        Image.open(best_path).convert("RGB"),
        Image.open(lora_path).convert("RGB"),
    ]
    titles = ["Original", "Best prompt (phase2)", "LoRA (phase3)"]
    return images, titles

fail_ids = df_fails["image_id"].tolist()
n_show   = 35
fig, axes = plt.subplots(n_show, 3, figsize=(10, n_show * 3.5))

for i, image_id in enumerate(fail_ids[:n_show]):
    images, titles = show_comparison(
        image_id, df_clip, LORA_OUTPUTS_DIR, INPUTS_DIR, OUTPUTS_DIR
    )
    for j, (img, title) in enumerate(zip(images, titles)):
        axes[i, j].imshow(img.resize((256, 256)))
        axes[i, j].axis("off")
        if i == 0:
            axes[i, j].set_title(title, fontsize=11, fontweight="bold")
    axes[i, 0].set_ylabel(
        f"{image_id}\n({df_fails[df_fails.image_id == image_id].notes.values[0]})",
        fontsize=8, rotation=0, labelpad=100, va="center"
    )

plt.suptitle("Failure recovery — Best prompt vs LoRA", fontsize=13, fontweight="bold", y=1.01)
plt.tight_layout()
plt.savefig(LORA_OUTPUT_DIR / "phase3_failure_comparison.png", dpi=120, bbox_inches="tight")
plt.show()
print(f"Saved comparison grid.")

clip_model     = CLIPModel.from_pretrained("openai/clip-vit-base-patch32").to(device)
clip_processor = CLIPProcessor.from_pretrained("openai/clip-vit-base-patch32")

POSITIVE_PROMPT = "a person with a short beard"
NEGATIVE_PROMPT = "a person without a beard"

@torch.no_grad()
def clip_score(image: Image.Image, positive: str, negative: str) -> dict:
    inputs = clip_processor(
        text=[positive, negative], images=image, return_tensors="pt", padding=True
    ).to(device)
    logits = clip_model(**inputs).logits_per_image.softmax(dim=1)[0]
    return {
        "clip_target_score":   logits[0].item(),
        "clip_negative_score": logits[1].item(),
        "clip_contrast_score": (logits[0] - logits[1]).item(),
    }

@torch.no_grad()
def clip_preservation(original: Image.Image, edited: Image.Image) -> float:
    inputs = clip_processor(images=[original, edited], return_tensors="pt").to(device)
    feats  = clip_model.get_image_features(**inputs)
    feats  = feats / feats.norm(dim=-1, keepdim=True)
    return (feats[0] @ feats[1]).item()

clip_lora_rows = []
for _, row in tqdm(df_lora_results.iterrows(), total=len(df_lora_results)):
    orig  = Image.open(INPUTS_DIR / f"{row.image_id}.png").convert("RGB")
    lora  = Image.open(row.output_path).convert("RGB")
    scores = clip_score(lora, POSITIVE_PROMPT, NEGATIVE_PROMPT)
    scores["clip_preservation_score"] = clip_preservation(orig, lora)
    scores["image_id"]   = row.image_id
    scores["prompt_type"] = "lora"
    scores["edit_type"]   = "facial_hair"
    clip_lora_rows.append(scores)

df_clip_lora = pd.DataFrame(clip_lora_rows)
df_clip_lora.to_csv(LORA_OUTPUT_DIR / "phase3_clip_lora.csv", index=False)

# Compare CLIP scores: phase2_best vs lora on the failure subset
clip_phase2_fails = df_clip[
    (df_clip.edit_type == "facial_hair") &
    (df_clip.prompt_type == "best") &
    (df_clip.image_id.isin(df_fails.image_id))
][["image_id", "clip_target_score", "clip_contrast_score", "clip_preservation_score"]]

comp = clip_phase2_fails.merge(
    df_clip_lora[["image_id", "clip_target_score", "clip_contrast_score", "clip_preservation_score"]],
    on="image_id", suffixes=("_phase2", "_lora")
)

print("\n=== CLIP improvement on failure subset ===")
for col in ["clip_target_score", "clip_contrast_score", "clip_preservation_score"]:
    delta = (comp[f"{col}_lora"] - comp[f"{col}_phase2"]).mean()
    print(f"  Δ {col}: {delta:+.4f}")

print("\nPer-image summary:")
print(comp.round(3).to_string())

"""## Grid search"""

import os, json, time, gc
from pathlib import Path
from itertools import product
from copy import deepcopy

import torch
import torch.nn.functional as F
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from PIL import Image
from tqdm.auto import tqdm, trange

from diffusers import (
    StableDiffusionInstructPix2PixPipeline,
    DDPMScheduler,
    EulerAncestralDiscreteScheduler,
)
from diffusers.optimization import get_scheduler
from peft import LoraConfig, get_peft_model
from torch.utils.data import DataLoader
from accelerate import Accelerator


GRID_ROOT = PHASE2_DIR / "phase3_lora_facial_hair" / "grid_search"
GRID_ROOT.mkdir(parents=True, exist_ok=True)

MODEL_ID    = "timbrooks/instruct-pix2pix"
EDIT_PROMPT = "Add a short beard around the chin and jaw"
RESOLUTION  = 256
SEED        = 42
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"

# Grid definition
#
# Axes chosen for maximum signal / minimal redundancy:
#
#   r            : capacity — 4 (low, less overfit) vs 8 (your baseline)
#   lora_alpha   : scale = alpha/r — "1.0×" (=r) vs "2.0×" (=2r)
#   lr           : step size — 2e-6 (conservative) vs 5e-6 (your baseline)
#   epochs       : 80 (early stop) vs 120 (your baseline)
#   image_guidance: inference identity anchor — 1.5 vs 1.7 (your baseline)
#
# 2 × 2 × 2 × 2 × 2 = 32 → pruned to 16 by fixing (alpha=r) as default
# and only crossing (r, lr, epochs, igs) so every axis is tested.

GRID = []
for r, lr, epochs, igs in product(
    [4, 8],           # lora r
    [2e-6, 5e-6],     # learning rate
    [80, 120],        # num epochs
    [1.5, 1.7],       # image_guidance_scale at inference
):
    GRID.append({
        "r":                    r,
        "lora_alpha":           r,          # scale = 1.0 throughout (cleanest baseline)
        "lora_dropout":         0.05,
        "lr":                   lr,
        "weight_decay":         1e-4,
        "num_epochs":           epochs,
        "warmup_steps":         max(20, int(0.05 * epochs * len(train_dataset))),
        "grad_accum_steps":     4,
        "batch_size":           1,
        "image_guidance_scale": igs,
        "guidance_scale":       7.5,
        "inference_steps":      25,
        "target_modules":       ["to_q", "to_k", "to_v", "to_out.0"],
    })

print(f"Total grid combos: {len(GRID)}")
for i, cfg in enumerate(GRID):
    print(f"  [{i:02d}] r={cfg['r']} α={cfg['lora_alpha']} "
          f"lr={cfg['lr']:.0e} ep={cfg['num_epochs']} igs={cfg['image_guidance_scale']}")


# build a fresh LoRA UNet

def build_lora_unet(base_unet, cfg):
    """Attach a fresh LoRA adapter to a *copy* of base_unet."""
    lora_cfg = LoraConfig(
        r=cfg["r"],
        lora_alpha=cfg["lora_alpha"],
        target_modules=cfg["target_modules"],
        lora_dropout=cfg["lora_dropout"],
        bias="none",
    )
    unet = get_peft_model(deepcopy(base_unet), lora_cfg)
    unet.print_trainable_parameters()
    return unet


# Helper: train one combo

def train_combo(cfg, combo_dir, base_unet, vae, text_encoder, tokenizer,
                noise_sched, train_dataset):
    """Train LoRA for one hyper-param config. Returns list of per-epoch losses."""

    combo_dir.mkdir(parents=True, exist_ok=True)

    unet = build_lora_unet(base_unet, cfg)

    accelerator = Accelerator(
        gradient_accumulation_steps=cfg["grad_accum_steps"],
        mixed_precision="no",
    )

    train_loader = DataLoader(
        train_dataset, batch_size=cfg["batch_size"], shuffle=True
    )

    optimizer = torch.optim.AdamW(
        filter(lambda p: p.requires_grad, unet.parameters()),
        lr=cfg["lr"],
        weight_decay=cfg["weight_decay"],
        betas=(0.9, 0.999),
    )

    lr_scheduler = get_scheduler(
        "constant_with_warmup",
        optimizer=optimizer,
        num_warmup_steps=cfg["warmup_steps"],
        num_training_steps=cfg["num_epochs"] * len(train_loader),
    )

    unet, optimizer, train_loader, lr_scheduler = accelerator.prepare(
        unet, optimizer, train_loader, lr_scheduler
    )
    vae.to(accelerator.device)
    text_encoder.to(accelerator.device)

    def encode_text(prompt):
        tokens = tokenizer(
            prompt, padding="max_length",
            max_length=tokenizer.model_max_length,
            truncation=True, return_tensors="pt",
        ).input_ids.to(accelerator.device)
        with torch.no_grad():
            return text_encoder(tokens).last_hidden_state

    losses     = []
    best_loss  = float("inf")
    unet.train()

    epoch_bar = trange(cfg["num_epochs"], desc="  epochs", leave=False)
    for epoch in epoch_bar:
        epoch_loss = 0.0

        for batch in train_loader:
            with accelerator.accumulate(unet):
                orig_px = batch["original_pixel_values"].to(accelerator.device)
                edit_px = batch["edited_pixel_values"].to(accelerator.device)

                orig_lat = vae.encode(orig_px).latent_dist.sample() * vae.config.scaling_factor
                edit_lat = vae.encode(edit_px).latent_dist.sample() * vae.config.scaling_factor

                noise     = torch.randn_like(edit_lat)
                bsz       = edit_lat.shape[0]
                timesteps = torch.randint(
                    0, noise_sched.config.num_train_timesteps,
                    (bsz,), device=accelerator.device,
                ).long()
                noisy_lat = noise_sched.add_noise(edit_lat, noise, timesteps)

                model_input = torch.cat([noisy_lat, orig_lat], dim=1)
                enc_hidden  = encode_text(EDIT_PROMPT)

                noise_pred = unet(model_input, timesteps,
                                  encoder_hidden_states=enc_hidden).sample
                loss = F.mse_loss(noise_pred, noise)

                accelerator.backward(loss)
                accelerator.clip_grad_norm_(unet.parameters(), 1.0)
                optimizer.step()
                lr_scheduler.step()
                optimizer.zero_grad()

                epoch_loss += loss.item()

        avg = epoch_loss / len(train_loader)
        losses.append(avg)
        epoch_bar.set_postfix(loss=f"{avg:.4f}")

        if avg < best_loss:
            best_loss = avg
            unwrapped = accelerator.unwrap_model(unet)
            unwrapped.save_pretrained(combo_dir / "unet_lora_best")

    # Save loss curve
    fig, ax = plt.subplots(figsize=(7, 3))
    ax.plot(losses, linewidth=1.5, color="#e05c3a")
    ax.set_xlabel("Epoch"); ax.set_ylabel("MSE loss")
    label = (f"r={cfg['r']}  α={cfg['lora_alpha']}  "
             f"lr={cfg['lr']:.0e}  ep={cfg['num_epochs']}")
    ax.set_title(f"LoRA loss — {label}", fontsize=10)
    ax.grid(alpha=0.3)
    plt.tight_layout()
    fig.savefig(combo_dir / "loss_curve.png", dpi=100)
    plt.close(fig)

    # Save config
    cfg_save = {k: (v if not isinstance(v, list) else v) for k, v in cfg.items()}
    cfg_save["best_train_loss"] = float(best_loss)
    with open(combo_dir / "config.json", "w") as f:
        json.dump(cfg_save, f, indent=2)

    # Clean up to free VRAM
    del unet, optimizer, train_loader, lr_scheduler, accelerator
    torch.cuda.empty_cache(); gc.collect()

    return losses, best_loss


def run_inference_and_grid(cfg, combo_dir, df_fails, df_clip,
                           pipe_base, lora_config_cls):
    """Load LoRA adapter, run on fail images, save 3-col grid."""

    # Build inference pipe
    pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
        MODEL_ID, torch_dtype=torch.float16, safety_checker=None
    ).to(DEVICE)
    pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)

    lora_cfg = LoraConfig(
        r=cfg["r"],
        lora_alpha=cfg["lora_alpha"],
        target_modules=cfg["target_modules"],
        lora_dropout=cfg["lora_dropout"],
        bias="none",
    )
    pipe.unet = get_peft_model(pipe.unet, lora_cfg)
    pipe.unet.load_adapter(str(combo_dir / "unet_lora_best"), adapter_name="default")
    pipe.unet.eval()

    lora_out_dir = combo_dir / "outputs"
    lora_out_dir.mkdir(exist_ok=True)

    n_show   = min(len(df_fails), 35)
    n_cols   = 3
    fig_h    = n_show * 3.0
    fig, axes = plt.subplots(n_show, n_cols, figsize=(10, fig_h))

    clip_scores = []

    for i, (_, row) in enumerate(df_fails.iloc[:n_show].iterrows()):
        input_img = Image.open(INPUTS_DIR / f"{row.image_id}.png").convert("RGB").resize(
            (RESOLUTION, RESOLUTION), Image.LANCZOS
        )

        generator = torch.Generator(device=DEVICE).manual_seed(SEED)
        with torch.autocast(DEVICE):
            lora_result = pipe(
                prompt=EDIT_PROMPT,
                image=input_img,
                num_inference_steps=cfg["inference_steps"],
                image_guidance_scale=cfg["image_guidance_scale"],
                guidance_scale=cfg["guidance_scale"],
                generator=generator,
            ).images[0]

        lora_result.save(lora_out_dir / f"{row.image_id}_lora.png")

        # Fetch best-prompt output from phase 2
        clip_rows = df_clip[
            (df_clip.image_id == row.image_id) &
            (df_clip.edit_type == "facial_hair") &
            (df_clip.prompt_type == "best")
        ]
        if len(clip_rows) == 0:
            best_img = input_img
        else:
            best_img = Image.open(clip_rows.iloc[0]["output_path"]).convert("RGB")

        for j, (img, title) in enumerate([
            (input_img,  "Original"),
            (best_img,   "Best prompt (P2)"),
            (lora_result,"LoRA (P3)"),
        ]):
            axes[i, j].imshow(img.resize((256, 256)))
            axes[i, j].axis("off")
            if i == 0:
                axes[i, j].set_title(title, fontsize=10, fontweight="bold")

        note = df_fails[df_fails.image_id == row.image_id].notes.values[0]
        axes[i, 0].set_ylabel(
            f"{row.image_id}\n({note})", fontsize=7,
            rotation=0, labelpad=95, va="center"
        )

    label = (f"r={cfg['r']}  α={cfg['lora_alpha']}  "
             f"lr={cfg['lr']:.0e}  ep={cfg['num_epochs']}  "
             f"igs={cfg['image_guidance_scale']}")
    plt.suptitle(f"Failure recovery — {label}", fontsize=11, fontweight="bold", y=1.002)
    plt.tight_layout()
    grid_path = combo_dir / "inference_grid.png"
    fig.savefig(grid_path, dpi=100, bbox_inches="tight")
    plt.close(fig)
    print(f"    Saved grid → {grid_path}")

    del pipe
    torch.cuda.empty_cache(); gc.collect()

    return clip_scores


#  Load shared frozen components
print("Loading frozen base model components (once)…")
_pipe_fp32 = StableDiffusionInstructPix2PixPipeline.from_pretrained(
    MODEL_ID, torch_dtype=torch.float32, safety_checker=None
)
BASE_UNET        = _pipe_fp32.unet.cpu()
BASE_VAE         = _pipe_fp32.vae.cpu()
BASE_TEXT_ENC    = _pipe_fp32.text_encoder.cpu()
BASE_TOKENIZER   = _pipe_fp32.tokenizer
BASE_NOISE_SCHED = DDPMScheduler.from_pretrained(MODEL_ID, subfolder="scheduler")

BASE_UNET.requires_grad_(False)
BASE_VAE.requires_grad_(False)
BASE_TEXT_ENC.requires_grad_(False)

del _pipe_fp32
torch.cuda.empty_cache(); gc.collect()
print("Frozen components ready.")


#  Main grid-search loop
summary_rows = []

outer_bar = tqdm(enumerate(GRID), total=len(GRID), desc="Grid combos")
for combo_idx, cfg in outer_bar:
    label = (f"r={cfg['r']} α={cfg['lora_alpha']} "
             f"lr={cfg['lr']:.0e} ep={cfg['num_epochs']} "
             f"igs={cfg['image_guidance_scale']}")
    outer_bar.set_description(f"[{combo_idx:02d}/{len(GRID)}] {label}")

    combo_dir = GRID_ROOT / (
        f"combo_{combo_idx:02d}_r{cfg['r']}_a{cfg['lora_alpha']}_"
        f"lr{cfg['lr']:.0e}_e{cfg['num_epochs']}_igs{cfg['image_guidance_scale']}"
    )

    t0 = time.time()

    # Train
    print(f"\n{'─'*70}")
    print(f"[{combo_idx:02d}] TRAINING  {label}")
    print(f"{'─'*70}")

    losses, best_loss = train_combo(
        cfg, combo_dir,
        deepcopy(BASE_UNET),       # fresh copy each combo
        deepcopy(BASE_VAE),
        deepcopy(BASE_TEXT_ENC),
        BASE_TOKENIZER,
        BASE_NOISE_SCHED,
        train_dataset,
    )

    train_time = time.time() - t0
    print(f"  Training done in {train_time/60:.1f} min  |  best_loss={best_loss:.4f}")

    # Inference + grid
    print(f"[{combo_idx:02d}] INFERENCE {label}")
    t1 = time.time()

    _ = run_inference_and_grid(
        cfg, combo_dir, df_fails, df_clip,
        None, LoraConfig,
    )

    infer_time = time.time() - t1
    total_time = time.time() - t0
    print(f"  Inference done in {infer_time/60:.1f} min  |  total={total_time/60:.1f} min")

    row = {
        "combo_idx":            combo_idx,
        "r":                    cfg["r"],
        "lora_alpha":           cfg["lora_alpha"],
        "lr":                   cfg["lr"],
        "num_epochs":           cfg["num_epochs"],
        "image_guidance_scale": cfg["image_guidance_scale"],
        "best_train_loss":      best_loss,
        "train_time_min":       round(train_time / 60, 2),
        "infer_time_min":       round(infer_time / 60, 2),
        "combo_dir":            str(combo_dir),
    }
    summary_rows.append(row)

    # Save CSV after every combo so progress isn't lost on crash/timeout
    df_summary = pd.DataFrame(summary_rows)
    df_summary.to_csv(GRID_ROOT / "grid_summary.csv", index=False)
    print(f"  Summary CSV updated ({len(summary_rows)}/{len(GRID)} combos).")

print("\n" + "═"*70)
print("GRID SEARCH COMPLETE")
print("═"*70)

df_summary = pd.read_csv(GRID_ROOT / "grid_summary.csv")
print(df_summary.sort_values("best_train_loss").to_string())


# visualisation
fig, axes = plt.subplots(1, 4, figsize=(18, 4))

for ax, col, title in zip(
    axes,
    ["r", "lr", "num_epochs", "image_guidance_scale"],
    ["LoRA rank (r)", "Learning rate", "Num epochs", "Image guidance scale"],
):
    grouped = df_summary.groupby(col)["best_train_loss"].mean()
    bars = ax.bar([str(k) for k in grouped.index], grouped.values,
                  color="#4a90d9", edgecolor="white", linewidth=0.8)
    ax.bar_label(bars, fmt="%.4f", fontsize=8, padding=2)
    ax.set_title(title, fontsize=10, fontweight="bold")
    ax.set_ylabel("Avg best train loss")
    ax.grid(axis="y", alpha=0.3)

plt.suptitle("Grid search — mean best loss per hyper-param value",
             fontsize=12, fontweight="bold")
plt.tight_layout()
fig.savefig(GRID_ROOT / "grid_summary_plot.png", dpi=120, bbox_inches="tight")
plt.show()
print(f"Saved summary plot → {GRID_ROOT / 'grid_summary_plot.png'}")

best_row = df_summary.sort_values("best_train_loss").iloc[0]
print("\n  Best combo:")
for k, v in best_row.items():
    print(f"   {k:30s}: {v}")

import torch.nn.functional as F

@torch.no_grad()
def clip_identity_similarity(img_a: Image.Image, img_b: Image.Image) -> float:

    inputs = clip_processor(
        images=[img_a, img_b],
        return_tensors="pt"
    ).to(device)

    outputs = clip_model.vision_model(pixel_values=inputs["pixel_values"])

    # CLS token embeddings (correct identity representation)
    feats = outputs.pooler_output  # shape: (2, hidden_dim)

    feats = F.normalize(feats, p=2, dim=-1)

    return float((feats[0] @ feats[1]).item())

# Best-LoRA Selection Helper
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from pathlib import Path
from PIL import Image

# Best combo dir from grid search
BEST_COMBO_DIR = (
    PHASE2_DIR
    / "phase3_lora_facial_hair"
    / "grid_search"
    / "combo_11_r8_a8_lr2e-06_e120_igs1.7"
)
LORA_OUTPUTS_DIR = BEST_COMBO_DIR / "outputs"

RESOLUTION = 256

def load_or_blank(path, size=RESOLUTION):
    p = Path(path)
    if p.exists():
        return Image.open(p).convert("RGB").resize((size, size), Image.LANCZOS)
    return Image.new("RGB", (size, size), (30, 30, 46))

fail_ids = df_fails["image_id"].tolist()

n = len(fail_ids)
n_cols = 3
fig, axes = plt.subplots(n, n_cols, figsize=(11, n * 3.4))

print(f"Rendering {n} cases — orig / phase2-best / LoRA (combo 11) …")

scores = {}

for i, image_id in enumerate(fail_ids):

    orig_path = INPUTS_DIR / f"{image_id}.png"

    clip_rows = df_clip[
        (df_clip.image_id == image_id) &
        (df_clip.edit_type == "facial_hair") &
        (df_clip.prompt_type == "best")
    ]

    best_path = (
        Path(clip_rows.iloc[0]["output_path"])
        if len(clip_rows) > 0
        else OUTPUTS_DIR / f"{image_id}_facial_hair_best.png"
    )

    lora_path = LORA_OUTPUTS_DIR / f"{image_id}_lora.png"

    orig = load_or_blank(orig_path)
    best = load_or_blank(best_path)
    lora = load_or_blank(lora_path)

    #CLIP identity scores
    p2_clip   = clip_identity_similarity(orig, best)
    lora_clip = clip_identity_similarity(orig, lora)

    improvement = lora_clip - p2_clip

    scores[image_id] = {
        "p2_clip": round(p2_clip, 4),
        "lora_clip": round(lora_clip, 4),
        "improvement": round(improvement, 4),
    }

    note = df_fails[df_fails.image_id == image_id].notes.values[0]

    for j, (img, title) in enumerate(zip(
        [orig, best, lora],
        ["Original", "Phase 2 best", "LoRA (combo 11)"],
    )):
        ax = axes[i, j]
        ax.imshow(img)
        ax.axis("off")
        if i == 0:
            ax.set_title(title, fontsize=10, fontweight="bold")

    axes[i, 0].set_ylabel(
        f"[{i:02d}] {image_id}\n({note})",
        fontsize=7,
        rotation=0,
        labelpad=100,
        va="center",
        fontfamily="monospace",
    )

    if improvement > 0.03:
        color = "#00e676"
        tag = f"✓ ID +{improvement:.3f}"
    elif improvement > 0.01:
        color = "#ffeb3b"
        tag = f"~ ID +{improvement:.3f}"
    elif p2_clip < 0.75 and lora_clip < 0.75:
        color = "#ff5252"
        tag = f"✗ both weak ({p2_clip:.2f})"
    else:
        color = "#aaaacc"
        tag = "≈ neutral"

    for spine in axes[i, 2].spines.values():
        spine.set_edgecolor(color)
        spine.set_linewidth(2.5)
        spine.set_visible(True)

    axes[i, 2].set_title(tag, fontsize=7, color=color, pad=2)


legend_patches = [
    mpatches.Patch(color="#00e676", label="Strong identity improvement (LoRA wins)"),
    mpatches.Patch(color="#ffeb3b", label="Mild improvement"),
    mpatches.Patch(color="#ff5252", label="Failure cases"),
    mpatches.Patch(color="#aaaacc", label="Neutral"),
]

fig.legend(
    handles=legend_patches,
    loc="lower center",
    ncol=4,
    fontsize=8,
    framealpha=0.9,
    bbox_to_anchor=(0.5, -0.01),
)

plt.suptitle(
    "LoRA output browser — CLIP-based identity preservation\n"
    "Pick green rows for retraining",
    fontsize=11,
    fontweight="bold",
    y=1.002,
)

plt.tight_layout()

browser_path = BEST_COMBO_DIR / "selection_browser_clip.png"
fig.savefig(browser_path, dpi=110, bbox_inches="tight")
plt.show()

print(f"\nSaved browser grid → {browser_path}")


# ranking table
df_scores = pd.DataFrame(scores).T.sort_values(
    "improvement",
    ascending=False
)
df_scores.index.name = "image_id"

print("\n── CLIP Identity Improvement Ranking ──────────────────")
print(df_scores.to_string())

print("\nTop candidates for retraining (improvement > 0.03):")
top = df_scores[df_scores.improvement > 0.03]
print(top.index.tolist())


improved = (df_scores["improvement"] > 0).sum()
total = len(df_scores)

print("\n── SUMMARY (CLIP IDENTITY) ──────────────────")
print(f"Improved cases: {improved}/{total}")
print(f"Mean Δ CLIP identity: {df_scores['improvement'].mean():+.4f}")
print(f"Worst regression: {df_scores['improvement'].min():+.4f}")
print(f"Best improvement: {df_scores['improvement'].max():+.4f}")

# Shows top-N candidates ranked by identity improvement score
# 4 columns: Original | Phase2 Best | LoRA Output | Diff heatmap

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from pathlib import Path
from PIL import Image

BEST_COMBO_DIR   = (
    PHASE2_DIR
    / "phase3_lora_facial_hair"
    / "grid_search"
    / "combo_11_r8_a8_lr2e-06_e120_igs1.7"
)
LORA_OUTPUTS_DIR = BEST_COMBO_DIR / "outputs"
RESOLUTION       = 256
TOP_N            = 21

def load_or_blank(path, size=RESOLUTION):
    p = Path(path)
    if p.exists():
        return Image.open(p).convert("RGB").resize((size, size), Image.LANCZOS)
    blank = Image.new("RGB", (size, size), (30, 30, 46))
    return blank

def pixel_drift(a, b):
    a_ = np.array(a).astype(float) / 255.0
    b_ = np.array(b).astype(float) / 255.0
    return float(np.mean(np.abs(a_ - b_)))

def diff_heatmap(orig_img, lora_img):
    a = np.array(orig_img).astype(float) / 255.0
    b = np.array(lora_img).astype(float) / 255.0
    diff = np.mean(np.abs(a - b), axis=2)          # (H, W)
    diff_norm = (diff - diff.min()) / (diff.max() - diff.min() + 1e-8)
    cmap  = plt.get_cmap("RdYlGn_r")               # red=changed, green=preserved
    hmap  = (cmap(diff_norm)[:, :, :3] * 255).astype(np.uint8)
    return Image.fromarray(hmap)

# ── Build ranked candidate list ───────────────────────────────────────────────
TOP_CANDIDATES = [
    'ffhq_sample_0050', 'ffhq_sample_0169', 'ffhq_sample_0018',
    'ffhq_sample_0188', 'ffhq_sample_0144', 'ffhq_sample_0075',
    'ffhq_sample_0057', 'ffhq_sample_0193', 'ffhq_sample_0198',
    'ffhq_sample_0095', 'ffhq_sample_0108', 'ffhq_sample_0073',
    'ffhq_sample_0109', 'ffhq_sample_0033', 'ffhq_sample_0044',
    'ffhq_sample_0051', 'ffhq_sample_0164', 'ffhq_sample_0006',
    'ffhq_sample_0005', 'ffhq_sample_0142', 'ffhq_sample_0163',
][:TOP_N]

# Recompute scores for ranking
ranked = []
for image_id in TOP_CANDIDATES:
    orig_path = INPUTS_DIR / f"{image_id}.png"
    clip_rows = df_clip[
        (df_clip.image_id == image_id) &
        (df_clip.edit_type == "facial_hair") &
        (df_clip.prompt_type == "best")
    ]
    best_path = (
        Path(clip_rows.iloc[0]["output_path"]) if len(clip_rows) > 0
        else OUTPUTS_DIR / f"{image_id}_facial_hair_best.png"
    )
    lora_path = LORA_OUTPUTS_DIR / f"{image_id}_lora.png"

    orig = load_or_blank(orig_path)
    best = load_or_blank(best_path)
    lora = load_or_blank(lora_path)

    p2_drift   = pixel_drift(orig, best)
    lora_drift = pixel_drift(orig, lora)
    improvement = p2_drift - lora_drift

    ranked.append({
        "image_id":    image_id,
        "orig":        orig,
        "best":        best,
        "lora":        lora,
        "p2_drift":    round(p2_drift,    3),
        "lora_drift":  round(lora_drift,  3),
        "improvement": round(improvement, 3),
    })

ranked.sort(key=lambda x: x["improvement"], reverse=True)

N_COLS  = 4   # orig | p2 | lora | heatmap
N_ROWS  = len(ranked)
CELL    = 2.7

fig, axes = plt.subplots(
    N_ROWS, N_COLS,
    figsize=(CELL * N_COLS + 1.2, CELL * N_ROWS + 0.6),
    facecolor="#0d0d18",
)

COL_TITLES = ["Original", "Phase 2 best", "LoRA output", "Change map\n(red=changed)"]

for i, rec in enumerate(ranked):
    images = [rec["orig"], rec["best"], rec["lora"],
              diff_heatmap(rec["orig"], rec["lora"])]

    # Row-level quality indicator
    imp = rec["improvement"]
    if imp > 0.08:
        quality, q_color = "strong fix", "#00e676"
    elif imp > 0.05:
        quality, q_color = "good fix",   "#ffeb3b"
    else:
        quality, q_color = "mild fix",   "#64b5f6"

    for j, img in enumerate(images):
        ax = axes[i, j]
        ax.imshow(img)
        ax.axis("off")
        ax.set_facecolor("#0d0d18")

        # Column titles on first row only
        if i == 0:
            ax.set_title(COL_TITLES[j], fontsize=8.5, color="#ccccdd",
                         fontweight="bold", pad=4)

        if j == 2:
            for spine in ax.spines.values():
                spine.set_visible(True)
                spine.set_edgecolor(q_color)
                spine.set_linewidth(2.5)

    # Row label
    label = (
        f"#{i+1}  {rec['image_id']}\n"
        f"P2 drift={rec['p2_drift']:.3f}  "
        f"LoRA drift={rec['lora_drift']:.3f}  "
        f"Δ={rec['improvement']:+.3f}  {quality}"
    )
    axes[i, 0].set_ylabel(
        label, fontsize=6.5, color=q_color,
        rotation=0, labelpad=185, va="center",
        fontfamily="monospace",
    )

plt.suptitle(
    f"Top {len(ranked)} LoRA candidates — ranked by identity improvement\n"
    "Pick the ones where LoRA column shows correct person + natural beard",
    fontsize=10, fontweight="bold", color="white", y=1.002,
)
plt.tight_layout(h_pad=0.4, w_pad=0.3)

out_path = BEST_COMBO_DIR / "top_candidates_inspection.png"
fig.savefig(out_path, dpi=115, bbox_inches="tight", facecolor=fig.get_facecolor())
plt.show()
print(f"\nSaved → {out_path}")
print("\nNow fill MANUAL_LORA_PICKS in Cell B with the IDs you want to keep.")

"""## Latent injection

Alternative to LoRA fine-tuning, adapted from *"Structure-Preserving Zero-Shot Image Editing via
Stage-Wise Latent Injection in Diffusion Models."*

- **Idea:** identity drift happens mostly in early denoising steps, while structure (face, skin tone, hair, background) is still being decided
- **Approach:** for the first `inject_until` fraction of steps, blend the generated latent with a mix of the noised source latent + a noised reference latent (with the target attribute already present)
- **Schedule:** blend strength `inject_alpha` decays over the injection window (cosine), then denoising proceeds normally so the edit can still form
- **Tuning:** pilot grid search over `(inject_until, inject_alpha)` on a subset of failure cases, using pixel drift as an identity-preservation proxy
- **Evaluation:** best setting applied to the full failure set, compared against Phase 2 best-prompt and Phase 3 LoRA results
"""

from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path
from PIL import Image
import pandas as pd
import matplotlib.pyplot as plt

PROJECT_DIR = Path("/content/drive/MyDrive/adobe_phase1_failure_analysis")
METADATA_DIR = PROJECT_DIR / "metadata"

FILLED_LABEL_CSV = METADATA_DIR / "sample_200_labels_FILLED.csv"

df = pd.read_csv(FILLED_LABEL_CSV)

for col in ["has_glasses", "has_facial_hair", "usable"]:
    df[col] = df[col].astype(int)

REFERENCE_SAMPLE_ID = "ffhq_sample_0149"

ref_row = df[
    (df["sample_id"] == REFERENCE_SAMPLE_ID)
    & (df["has_facial_hair"] == 1)
    & (df["usable"] == 1)
]

if len(ref_row) == 0:
    raise ValueError(
        f"{REFERENCE_SAMPLE_ID} not found or does not have facial hair."
    )

ref_row = ref_row.iloc[0]

reference_image_path = ref_row["image_path"]

reference_image = (
    Image.open(reference_image_path)
    .convert("RGB")
    .resize((512, 512))
)

print("Reference image:", REFERENCE_SAMPLE_ID)
print("Path:", reference_image_path)

plt.figure(figsize=(4,4))
plt.imshow(reference_image)
plt.axis("off")
plt.title(f"Reference: {REFERENCE_SAMPLE_ID}")
plt.show()

from torchvision import transforms
import torch

def encode_image(img):

    transform = transforms.Compose([
        transforms.Resize((512, 512)),
        transforms.ToTensor(),
    ])

    image = transform(img).unsqueeze(0)
    image = image.to(device=device, dtype=dtype)

    image = image * 2 - 1  # [0,1] -> [-1,1]

    with torch.no_grad():
        latent = pipe.vae.encode(image).latent_dist.sample()
        latent = latent * pipe.vae.config.scaling_factor

    return latent

import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
dtype = torch.float16 if device == "cuda" else torch.float32


ref_latent = encode_image(reference_image)

print(ref_latent.shape)

import os
import itertools
import torch
import pandas as pd
import matplotlib.pyplot as plt
import math
import torchvision.transforms as T

from pathlib import Path
from PIL import Image
from tqdm.auto import tqdm

from diffusers import (
    StableDiffusionInstructPix2PixPipeline,
    EulerAncestralDiscreteScheduler,
)

PHASE4_DIR = PHASE2_DIR / "phase4_latent_injection"
PHASE4_DIR.mkdir(parents=True, exist_ok=True)

EDIT_PROMPT = "Add a short beard around the chin and jaw"
MODEL_ID    = "timbrooks/instruct-pix2pix"
RESOLUTION  = 256
DEVICE      = "cuda" if torch.cuda.is_available() else "cpu"
DTYPE       = torch.float16 if DEVICE == "cuda" else torch.float32
SEED        = 42

# Load pipeline
print("Loading instruct-pix2pix pipeline...")
pipe = StableDiffusionInstructPix2PixPipeline.from_pretrained(
    MODEL_ID,
    torch_dtype=DTYPE,
    safety_checker=None,
).to(DEVICE)

# EulerAncestral is more stable than DDIM for ip2p
pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(
    pipe.scheduler.config
)
pipe.enable_attention_slicing()
print("Pipeline ready.")

GUIDANCE_SCALE       = 6.0
IMAGE_GUIDANCE_SCALE = 2.2   # best from grid search
NUM_STEPS            = 40    # slightly more than 25 for better structure

# Grid to search
# inject_until : fraction of steps where injection is active
#                low  (0.1) = subtle anchor, more edit freedom
#                high (0.4) = strong anchor, less edit freedom
# inject_alpha : blend strength at step 0 (decays linearly to 0)
#                low  (0.3) = gentle nudge
#                high (0.7) = hard constraint

INJECT_GRID = list(itertools.product(
    [0.25, 0.3, 0.35, 0.4],   # was [0.1, 0.2, 0.3, 0.4]
    [0.4, 0.5, 0.6],           # was [0.3, 0.5, 0.7]
))
print(f"Grid size: {len(INJECT_GRID)} combos")

# ── Helpers ───────────────────────────────────────────────────────────────────
def make_generator():
    return torch.Generator(device=DEVICE).manual_seed(SEED)

def encode_image(pil_img):
    tf = T.Compose([
        T.Resize(RESOLUTION, interpolation=T.InterpolationMode.LANCZOS),
        T.CenterCrop(RESOLUTION),
        T.ToTensor(),
        T.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
    ])
    x = tf(pil_img).unsqueeze(0).to(DEVICE, dtype=DTYPE)
    with torch.no_grad():
        latent = pipe.vae.encode(x).latent_dist.mean
    return latent * pipe.vae.config.scaling_factor

def pixel_drift(img_a, img_b):
    import numpy as np
    a = np.array(img_a.resize((RESOLUTION, RESOLUTION))).astype(float) / 255.0
    b = np.array(img_b.resize((RESOLUTION, RESOLUTION))).astype(float) / 255.0
    return float(np.mean(np.abs(a - b)))

def run_with_injection(image, inject_until, inject_alpha):
    src_latent = encode_image(image)
    ref_latent = encode_image(reference_image)

    pipe.scheduler.set_timesteps(NUM_STEPS, device=DEVICE)
    timesteps = pipe.scheduler.timesteps

    torch.manual_seed(SEED)
    fixed_noise = torch.randn_like(src_latent)

    def get_noisy_latent(latent, t):

        t_cpu = t.cpu().long() if isinstance(t, torch.Tensor) else int(t)

        alpha_bar = pipe.scheduler.alphas_cumprod[t_cpu].to(
            device=DEVICE,
            dtype=latent.dtype
        )

        alpha_bar = alpha_bar.view(1, 1, 1, 1)

        return (
            torch.sqrt(alpha_bar) * latent
            + torch.sqrt(1.0 - alpha_bar) * fixed_noise
        )

    inject_steps = max(1, int(inject_until * NUM_STEPS))

    structural_latents = {}

    for i in range(inject_steps):

        src_noisy = get_noisy_latent(
            src_latent,
            timesteps[i]
        )

        ref_noisy = get_noisy_latent(
            ref_latent,
            timesteps[i]
        )

        # Mostly preserve source identity
        # Small amount of beard information
        mixed = (
            0.90 * src_noisy
            + 0.10 * ref_noisy
        )

        structural_latents[i] = mixed
    def injection_callback(pipe_obj, step_index, timestep, kwargs):

        if step_index >= inject_steps:
            return kwargs

        current = kwargs["latents"]
        struct_lat = structural_latents[step_index]

        if struct_lat.shape != current.shape:
            struct_lat = torch.nn.functional.interpolate(
                struct_lat,
                size=current.shape[2:],
                mode="bilinear",
                align_corners=False,
            )

        progress = step_index / max(inject_steps - 1, 1)

        blend = (
            inject_alpha
            * 0.5
            * (1.0 + math.cos(math.pi * progress))
        )

        kwargs["latents"] = (
            blend * struct_lat.expand_as(current)
            + (1.0 - blend) * current
        )

        return kwargs

    result = pipe(
        prompt=EDIT_PROMPT,
        image=image,
        num_inference_steps=NUM_STEPS,
        guidance_scale=GUIDANCE_SCALE,
        image_guidance_scale=IMAGE_GUIDANCE_SCALE,
        generator=make_generator(),
        callback_on_step_end=injection_callback,
        callback_on_step_end_tensor_inputs=["latents"],
    ).images[0]

    return result

def run_baseline(image):
    """Plain ip2p, no injection — for comparison."""
    return pipe(
        prompt=EDIT_PROMPT,
        image=image,
        num_inference_steps=NUM_STEPS,
        guidance_scale=GUIDANCE_SCALE,
        image_guidance_scale=IMAGE_GUIDANCE_SCALE,
        generator=make_generator(),
    ).images[0]

# grid search on first 8 fail cases to find best (u, α)

PILOT_IDS  = df_fails["image_id"].tolist()[:8]
PILOT_DIR  = PHASE4_DIR / "pilot_grid"
PILOT_DIR.mkdir(exist_ok=True)

pilot_scores = []

print(f"\nRunning pilot grid ({len(INJECT_GRID)} combos × {len(PILOT_IDS)} images)...")

for inject_until, inject_alpha in tqdm(INJECT_GRID, desc="Grid combos"):
    tag     = f"u{inject_until}_a{inject_alpha}"
    out_dir = PILOT_DIR / tag
    out_dir.mkdir(exist_ok=True)

    drift_sum = 0.0
    for image_id in PILOT_IDS:
        orig = Image.open(INPUTS_DIR / f"{image_id}.png").convert("RGB")
        out  = run_with_injection(orig, inject_until, inject_alpha)
        out.save(out_dir / f"{image_id}.png")
        drift_sum += pixel_drift(orig, out)

    avg_drift = drift_sum / len(PILOT_IDS)
    pilot_scores.append({
        "inject_until": inject_until,
        "inject_alpha": inject_alpha,
        "avg_drift":    round(avg_drift, 4),
        "tag":          tag,
    })
    print(f"  u={inject_until} α={inject_alpha} → avg_drift={avg_drift:.4f}")

df_pilot = pd.DataFrame(pilot_scores).sort_values("avg_drift")
df_pilot.to_csv(PILOT_DIR / "pilot_scores.csv", index=False)
print("\nPilot grid scores (sorted by drift, lower = more identity preserved):")
print(df_pilot.to_string(index=False))

# Lowest drift = most identity preserved.
# But we also want some edit to happen (drift < 0.02 is suspiciously low).
df_valid = df_pilot[df_pilot.avg_drift > 0.02]
best_row  = df_valid.iloc[0]
BEST_U    = best_row["inject_until"]
BEST_A    = best_row["inject_alpha"]
print(f"\n Best combo: inject_until={BEST_U}  inject_alpha={BEST_A}  drift={best_row['avg_drift']:.4f}")

# Pilot visual grid (8 images × top-4 combos + baseline)

TOP4 = df_pilot.head(4)[["inject_until", "inject_alpha"]].values.tolist()

n_rows = len(PILOT_IDS)
n_cols = 2 + len(TOP4)   # orig + baseline + top4 combos
fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 2.8, n_rows * 2.8))

col_titles = (
    ["Original", "Baseline (no inject)"]
    + [f"u={u} α={a}" for u, a in TOP4]
)

print("\nRendering pilot visual grid...")
for i, image_id in enumerate(PILOT_IDS):
    orig     = Image.open(INPUTS_DIR / f"{image_id}.png").convert("RGB")
    baseline = run_baseline(orig)

    imgs = [orig, baseline] + [
        Image.open(PILOT_DIR / f"u{u}_a{a}" / f"{image_id}.png").convert("RGB")
        for u, a in TOP4
    ]

    for j, img in enumerate(imgs):
        ax = axes[i, j]
        ax.imshow(img.resize((RESOLUTION, RESOLUTION)))
        ax.axis("off")
        if i == 0:
            ax.set_title(col_titles[j], fontsize=8, fontweight="bold")
        if j == 0:
            note = df_fails[df_fails.image_id == image_id].notes.values[0]
            ax.set_ylabel(f"{image_id[:14]}\n({note})", fontsize=6.5,
                          rotation=0, labelpad=90, va="center", fontfamily="monospace")

plt.suptitle("Latent injection pilot — top 4 combos vs baseline",
             fontsize=11, fontweight="bold")
plt.tight_layout()
pilot_grid_path = PILOT_DIR / "pilot_visual_grid.png"
fig.savefig(pilot_grid_path, dpi=110, bbox_inches="tight")
plt.show()
print(f"Pilot grid saved → {pilot_grid_path}")

#Full inference

FULL_OUT_DIR = PHASE4_DIR / f"full_best_u{BEST_U}_a{BEST_A}"
FULL_OUT_DIR.mkdir(exist_ok=True)

fail_ids    = df_fails["image_id"].tolist()
full_results = []

print(f"\nRunning full inference on {len(fail_ids)} failures "
      f"(inject_until={BEST_U}, inject_alpha={BEST_A})...")

for image_id in tqdm(fail_ids, desc="Full inference"):
    orig = Image.open(INPUTS_DIR / f"{image_id}.png").convert("RGB")
    out  = run_with_injection(orig, BEST_U, BEST_A)
    out_path = FULL_OUT_DIR / f"{image_id}_latent_inject.png"
    out.save(out_path)
    full_results.append({
        "image_id":   image_id,
        "drift":      round(pixel_drift(orig, out), 4),
        "output_path": str(out_path),
    })

df_full = pd.DataFrame(full_results)
df_full.to_csv(FULL_OUT_DIR / "results.csv", index=False)
print(f"\nAverage drift: {df_full.drift.mean():.4f}")
print(f"Saved {len(df_full)} outputs → {FULL_OUT_DIR}")

#Full comparison grid

n_show = min(35, len(fail_ids))
n_cols = 4
fig, axes = plt.subplots(n_show, n_cols, figsize=(13, n_show * 3.2))

col_titles = ["Original", "Phase 2 best", "LoRA v2", "Latent inject"]

for i, image_id in enumerate(fail_ids[:n_show]):
    orig_path = INPUTS_DIR / f"{image_id}.png"

    clip_rows = df_clip[
        (df_clip.image_id == image_id) &
        (df_clip.edit_type == "facial_hair") &
        (df_clip.prompt_type == "best")
    ]
    p2_path = (
        Path(clip_rows.iloc[0]["output_path"]) if len(clip_rows) > 0
        else OUTPUTS_DIR / f"{image_id}_facial_hair_best.png"
    )

    lora_path   = LORA_OUTPUT_DIR/ f"{image_id}_facial_hair_lora.png"
    inject_path = FULL_OUT_DIR / f"{image_id}_latent_inject.png"

    def safe_load(p):
        p = Path(p)
        if p.exists():
            return Image.open(p).convert("RGB").resize((RESOLUTION, RESOLUTION))
        blank = Image.new("RGB", (RESOLUTION, RESOLUTION), (30, 30, 46))
        return blank

    imgs = [safe_load(orig_path), safe_load(p2_path),
            safe_load(lora_path), safe_load(inject_path)]

    note = df_fails[df_fails.image_id == image_id].notes.values[0]

    for j, img in enumerate(imgs):
        ax = axes[i, j]
        ax.imshow(img)
        ax.axis("off")
        if i == 0:
            ax.set_title(col_titles[j], fontsize=9, fontweight="bold")

    axes[i, 0].set_ylabel(
        f"{image_id}\n({note})",
        fontsize=7, rotation=0, labelpad=100, va="center", fontfamily="monospace"
    )

plt.suptitle(
    f"Phase 4 — 4-way comparison (latent inject: u={BEST_U} α={BEST_A})",
    fontsize=11, fontweight="bold", y=1.002,
)
plt.tight_layout()
comparison_path = FULL_OUT_DIR / "4way_comparison_grid.png"
fig.savefig(comparison_path, dpi=110, bbox_inches="tight")
plt.show()
print(f"4-way comparison grid saved → {comparison_path}")